### ISSUE TITLE
support "windows rules" (at least to automatically keep certain windows on all workspaces)

### ISSUE THREAD

**Issue by seanpk** [linuxmint/muffin#121]
Perhaps Muffin already supports it, in which case I think it needs to be better surfaced in the UI.

In compiz (Unity), KWin, and Xfwm (and maybe Metacity too) I can create a "windows rule" to customize many things about particular applications and types of windows for those applications and have the WM apply those rules automatically.

While I've done several subtle customization for a variety of windows, the one I miss most is to have my IM chat window(s) automatically set to be visible on all workspaces.

I would like to see such a feature added to Mutter.
- A prototype solution might be a way to hook in wmctrl commands (or I suppose any script) to a window creation event
- A polished solution would be to provide a control like the "Windows Rules" plugin for compiz
- An alternate solution would be to provide a simpler UI for the single feature of making certain windows appear on all desktops by default
  - (this might be as simple as an option on the window menu to save properties like "always on visible workspace" and even "always on top" to apply them the next time a window like the current one is created)

**Comment by feren** [comment]
+1

**Comment by nathan-b** [comment]
This is already there.

Go to preferences, and select Window. In the first option group, Buttons, add "Menu" to your title bar buttons (I added it as the first item on the left side, to match other window managers).

This will give each window a menu, which you can click to do stuff like move windows between workspaces, make windows available on all workspaces, or always sort them to the top of the z-order.

**Comment by feren** [comment]
Yeah, but it isn't permanent, we want the ability for variables to be automatically on on every window in certain criteria... (kinda like in KDE, it could also fix XWinWrap in Cinnamon too if done correctly...)

**Comment by nathan-b** [comment]
Ah, I see. Sorry for not reading carefully.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by erenfro** [comment]
It's kind of sad that this feature request was just ignored, and closed, without a second thought.  The mentioned KDE rules features are one reason that makes KDE so awesome. Similar functionality in Cinnamon would be fantastic, especially since every alternative that keeps coming out otherwise, devilspie, devilspie2, both basically now abandoned, and neither that good, or easy to work with, nor accurate.

Cinnamon could benefit strongly from this.
