### ISSUE TITLE
Adjustable (and multiple) default snap/tile split boundaries

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/muffin#124]
Working on a 1920x1080 screen (fairly common) something I've found is that most websites don't naturally adjust well to an exact 50:50 split (for example, GitHub itself wants to be slightly larger since sites optimize for 1024, not 960px), whereas the types of things you use in reference with them (terminal windows, text editors) don't have much reason to use half the screen in the first place.

It would be really great if it were possible to adjust the default window tiling boundaries, or preferably use multiple invocations of the snap/tile key combinations in the same direction to change the sizing of a window amongst several defaults.

i.e.

Super+Left (1st) = 2/3rd split, Super+Left = half split, Super+Left (2nd time) = 1/3rd split.

Obviously this behavior should be configurable, but it would allow adapting to some common use cases more easily, and possibly (via maybe a custom window size option) - some uncommon ones by further configuration by users.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by mohdismailmatasin** [comment]
https://www.reddit.com/r/linuxmint/s/PcDeYTb2V6
