### ISSUE TITLE
Centering New Windows Automatically in Cinnamon

### ISSUE THREAD

**Issue by AnishN** [linuxmint/muffin#129]
One feature that I would like to see implemented in linux mint is the ability to open new application windows in the center of the screen. Currently, it appears that the only options to do this are to use Gdevilspie to write a centering rule (which leads to an ugly flicker and is clunky) or to create a put window in center keyboard shortcut and use that. It would be nice to have an option to place windows in the center of the screen like in compiz. 

I took a look at the source code for muffin and have tried making changes to a few of the src files to match the existing options listed in dconf-edtior for window placement  in muffin (automatic, manual, and pointer) and added a new "center" mode. I am not sure how to test out these changes (it doesn't help that this is my first time working with c or github). Anyways, I have listed the changes that I made below. I hope that someone can test these out and that this feature can be incorporated into cinnamon. 

1 -  /muffin/src/core/place.c (Added a place in center function and an else if clause later on)

````
static gboolean
place_in_center(MetaWindow *window,
                 MetaFrameBorders *borders,
                 MetaPlacementMode placement_mode,
                 int *new_x,
                 int *new_y)
{
  int center_x, center_y;
  xi = meta_screen_get_current_monitor (window->screen);
  center_x = xi->rect.width / 2;
  center_y = xi->rect.height / 2;
  
  int window_width, window_height;
  window_width = window->frame ? window->frame->rect.width : window->rect.width;
  window_height = window->frame ? window->frame->rect.height : window->rect.height;

  if (borders) {
    *new_x = center_x + borders->visible.left - window_width / 2;
    *new_y = center_y + borders->visible.top  - window_height / 2;
  }
  else {
    *new_x = center_x - window_width / 2;
    *new_y = center_y - window_height / 2;
  }

  return TRUE;
}
````
...
````

    if (placement_mode == META_PLACEMENT_MODE_POINTER ||
      placement_mode == META_PLACEMENT_MODE_MANUAL)
    {
      if (place_by_pointer (window, borders, placement_mode, &x, &y))
        goto done_check_denied_focus;
    }

  else if (placement_mode == META_PLACEMENT_MODE_CENTER)
	{
	  if (place_in_center (window, borders, placement_mode, &x, &y))
        goto done_check_denied_focus;
	}
````

2 - /muffin/src/meta/common.h (Added an item to the list of placement options)

````
typedef enum
{
  META_PLACEMENT_MODE_AUTOMATIC,
  META_PLACEMENT_MODE_POINTER,
  META_PLACEMENT_MODE_MANUAL,
  META_PLACEMENT_MODE_CENTER
} MetaPlacementMode;
````

3 -  /muffin/src/org.cinnamon.muffin.gschema.xml (Edits the key description found in the dconf-editor)

````
<key name="placement-mode" enum="placement_type">
      <default>'automatic'</default>
      <_summary>Window placement mode</_summary>
      <_description>The window placement mode indicates how new windows
      are positioned. "automatic" means the system chooses a location
      automatically based on the space available on the desktop, or by
      a simple cascade if there is no space; "pointer" means that new
      windows are placed according to the mouse pointer position;
      "manual" means that the user must manually place the new window
      with the mouse or keyboard; "center" means that the system places
      new windows in the center of the desktop.</_description>
    </key>
````

**Comment by Paviluf** [comment]
I think that can be closed now
