### ISSUE TITLE
resizing tiled/snapped windows

### ISSUE THREAD

**Issue by Xylerone** [linuxmint/muffin#130]
The latest Cinnamon update on F20beta has left me with trouble resizing tiled/snapped windows.  If I try to resize by mouse using a side edge, the window will jump, maybe disapear, or maybe flip to the other side.  If I resize using a corner, top, or bottom edge then everything works fine.

Fedora 20beta cinnamon-2.0.13-3.fc20.x86_64

My system uses an Intel 4 Series Integrated Graphics Controller

**Comment by JosephMcc** [comment]
Can you guys still reproduce this issue. If not I'll go ahead and close it.

**Comment by Xylerone** [comment]
I can reproduce it only with Zukitwo Window Borders on F22 Cinnamon, and F23 Cinnamon Live (have not tried Mint 17.2).  I believe Zukitwo is the default window border used in F23 Cinnamon, but I'm OK switching to something else.

**Comment by JosephMcc** [comment]
This is an issue with the metacity theme. Switching to a different one will fix it.
