### ISSUE TITLE
feat request: more titlebar functions

### ISSUE THREAD

**Issue by geoffm** [linuxmint/muffin#133]
This is for Cinnamon settings / Windows options
Titlebars could be improved by adding, allo with 'menu', 'close' 'minimize' and 'maximize', buttons for 'toggle always on top" and 'toggle shade' (xfce does this, awesome useful).
Users could also be offered to use mouseWheelUp and mouseWheelDown to Roll up and down the window.
"Roll up and down window when scrolling on titlebar [X]" in Cinnamon/Windows options

**Comment by JosephMcc** [comment]
These are implemented. Your metacity theme needs to have support for the the various needed window icons for them to show.
