### ISSUE TITLE
Leaving tooltip if window is killed (or just closed)

### ISSUE THREAD

**Issue by ondrejkolin** [linuxmint/muffin#138]
When I drag a window and hold it for a while the "tooltip" for snapping?(dont know correct name) appears ... If window is killed or closed during ?snapping? the tooltip stay on screen. Reproduced on Cinnamon 2.0.14 Linux Mint 13 using xdotool windowkill. Originally apeared while using Google login in browser.

**Comment by icarter09** [comment]
@ondrejkolin are you still experiencing this issue?

**Comment by ondrejkolin** [comment]
Well, not really. Running on Wayland and Gnome Shell. If no one else is affected, feel free to close :-)
