### ISSUE TITLE
Edge resistance works using the edges of the Display, not the Screens

### ISSUE THREAD

**Issue by Hubro** [linuxmint/muffin#152]
In a multi-monitor setup with monitors of different resolutions, edge resistance only works on the edges of the _display_, as well as the edges between screens. Here's an illustration:

![illustration](https://cloud.githubusercontent.com/assets/597206/3361747/c99e25f4-fb01-11e3-8671-961798ab8e2a.png)

All the green edges provide edge resistance, but the red edge doesn't.

Notice also that the edges of the display that are outside the viewport of the screens still provide edge resistance.

**Comment by icarter09** [comment]
@Hubro are you still experiencing this issue?

**Comment by Hubro** [comment]
> @Hubro are you still experiencing this issue?

Sorry I have no idea, I haven't used Linux Mint for years.
