### ISSUE TITLE
Inability to make window titles/borders transparent

### ISSUE THREAD

**Issue by ShyPixie** [linuxmint/muffin#168]
Why muffin does not make window borders transparent? I try with the "alpha" attribute, but won't work.

**Comment by JosephMcc** [comment]
Transparency in the window decorations isn't supported as far as I know.

**Comment by Taariqq** [comment]
How about the ability to differently color the active window's title bar. Would be really helpful.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
