### ISSUE TITLE
regression regarding tiling

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/muffin#176]
Last week I upgraded to muffin 2.4.4 and i have to say it is a great improvement for gtk-apps with CSD, but i just discovered that there seems to be a tiling regression:

In muffin-2.4.3 it was possible for me to tile the gnome-system-monitor (3.14.1) to quarters, this doesn't work anymore, also yorba's california calendar app (0.3) doesn't tile anymore at all. 

I know there are problems regarding the minimum size of gtk-apps, but actually the calendar-app in unmaximized state is less wide than half of my screen as you can see in the picture below

<a href="http://de.tinypic.com?ref=2ci8m6q" target="_blank"><img src="http://i60.tinypic.com/2ci8m6q.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by mtwebster** [comment]
Yeah there's a mis-calculation going on where it's thinking c-s-d windows need more space than they actually do - they have invisible padding all around them (about 20px/side or so by gtk for shadow effects) normally, but the padding disappears when you tile.  I'll try to fix here soon.

**Comment by ManIVIctorious** [comment]
Good news, thanks
