### ISSUE TITLE
Add support for GTK decorations. 

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/muffin#177]
Gnome developers dropped metacity theme support in mutter so there is already at least one theme that doesn't have corresponding metacity theme - Adwaita. Moreover some features in metacity themes are broken since gtk 3.15 - e.g. gtk:bg[NORMAL] is not getting substituted anymore so simple copying of Adwaita metacity theme from old package doesn't work. 

So I propose to plan adding support for gtk decorations in one of the future releases.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
