### ISSUE TITLE
feature request - hide titlebars

### ISSUE THREAD

**Issue by Shudouken** [linuxmint/muffin#183]
Since cinnamon/muffin already supports dragging windows by holding the ALT key, it would be nice to have an option to eliminate titlebars alltogether. I've reassigned the 'close window' shortcut to ALT+q so I never use the titlebar's buttons anymore

There are shady ways to almost do this from other users wanting the same functionality (edit theme configs and reduce titlebar font to 1), but there's still a little border left no matter what is done.

**Comment by lestcape** [comment]
:+1: 

This code work for undecorate a window:
```
let screen = Gdk.Screen.get_default();
let gdk_win = screen.get_active_window();
if (gdk_win) {
     gdk_win.set_decorations(Gdk.WMDecoration.BORDER);
      let [x, y] = gdk_win.get_position();
      gdk_win.move(0,0);
      gdk_win.resize(gdk_win.get_width() + x, gdk_win.get_height() + y);
      gdk_win.unref();
}
```
This code work for decorate a window:
```
let screen = Gdk.Screen.get_default();
let gdk_win = screen.get_active_window();
if (gdk_win) {
     gdk_win.set_decorations(Gdk.WMDecoration.ALL);
     gdk_win.unref();
}
```
if we undecorate a windows, and then decorate it again all work as we want....

This secuence of code crash the applications:

undecorate window
restart cinnamon

Will be possible connect any signals to see if gdk windows are update and then update the internal representation of the windows, or will be possible add a new function for change the windows decoration from cjs?

Regards

**Comment by rbieb** [comment]
Agree, would be awesome to have that feature. The maximus extension does it, but it also causes cinnamon to segfault so it's not really a solution.

**Comment by goetzc** [comment]
For those interested, there is this other [Cinnamon Maximus](https://cinnamon-spices.linuxmint.com/extensions/view/29) extension which does work under Muffin 3.0.5.

**Comment by lestcape** [comment]
Access to X from the command line it's not a good idea... So, Maximus extension never will be a good solution and I’m not recommended the usage of this extension...

**Comment by lestcape** [comment]
https://github.com/jsparber/mutter-hide-legacy-decorations/blob/master/hideTitlebar.patch

**Comment by AleFelix** [comment]
I have made an applet for hiding the titlebar of the active windows based on the code provided by @lestcape https://github.com/AleFelix/cinnamon-applet-hide-title-bar

**Comment by lestcape** [comment]
@AleFelix when i wrote that, this won't exist in cinnamon:
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/main.js#L539

Idea: Capture the **shutdown** and re-add the decoration to all undecorate windows. If i remember correctly revert the decoration not cause i cinnamon crash.

**Comment by AleFelix** [comment]
@lestcape I will try to do it, for now I'm using a separate branch for testing the restoreAllTitleBars function.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
