### ISSUE TITLE
Attaching new windows to corners of screen

### ISSUE THREAD

**Issue by marlock9** [linuxmint/muffin#205]
In fact muffin now can only opens windows at pointer position or at the center (automatic looks like mix of both).
Please, improve automatic windows placement because it can't attach new windows to corners of screen.
I get: http://upyourpic.org/images/201509/7wljuop47w.png
Expected: http://upyourpic.org/images/201509/y6bkessvk4.png

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
