### ISSUE TITLE
There is tearing

### ISSUE THREAD

**Issue by RalfJung** [linuxmint/muffin#206]
When parts of a window, or windows that are not full-screen, are re-drawn, there is tearing. You can easily test this yourself with <https://www.ralfj.de/git/gltest.git>: If I maximize the window with the vertically moving bar, there is a tear line in the top quarter of the screen. Only if I go full-screen, the tearing disappears.
Tearing can also be seen when I scroll in Firefox, or when I move small windows around the screen quickly. You have to train your eye to see this. Unfortunately, I did, so I can't ignore this anymore...

The compositor should offer an option to completely get rid of all tearing. That's possible by doing a full-screen re-draw for every frame (if anything changed in that frame at all, that is), and using `glXSwapBuffer` for the update. I am using such a configuration for quite a while already with KWin (that can be configured appropriately), and it is working great. The additional work that has to be done because more things are re-drawn, is negligible at least in integrated GPUs. (Some users reported performance issues with NVidia drivers, which is why KWin doesn't do this per default.)

I am on an Intel HD graphics card. This driver doesn't support any other means of synchronizing with the vertical blank, like the older GL functions to manually wait for the blanks. Doing `glXSwapBuffer` is the only thing that can be done to get a tear-free update. The cost of the re-draws can be reduced by using the GLX_EXT_buffer_age extension, which however my version of the Intel Mesa drivers does not (yet?) support.

**Comment by rusty725** [comment]
have tearing as well on 2k monitor with gtx 970 oc card, the issue was fixed in mutter 3.18 to maintainer please fix it. Link http://www.phoronix.com/scan.php?page=news_item&px=GNOME-3.18-Mutter-NVIDIA

**Comment by JosephMcc** [comment]
@rusty725 These fixes are already in muffin for 2.8 https://github.com/linuxmint/muffin/commit/b4a62fae8e602d63381d9f7690e2e04c6b57005a

**Comment by rusty725** [comment]
greate thank you

**Comment by RalfJung** [comment]
I kind of doubt this will help on Intel drivers. As far as I know, these drivers do not support sync objects / fences to sync with the v-blank. The only way to get a tear-free update is to use SwapBuffers. Hence the compositor should do that whenever there's any change in the frame, or at least whenever the change is large enough to warrant re-drawing the entire frame. (Since SwapBuffers also avoids copying, it can often be cheaper to re-draw the full frame and do SwapBuffers, than to re-draw only some part of it and copy that to the current front buffer.)

I will report back when 2.8 lands in Debian, and I can test it.
