### ISSUE TITLE
[Feature request] allow window edge resistance to be disabled without recompile

### ISSUE THREAD

**Issue by dragonbytes** [linuxmint/muffin#217]
hi, could you please implement a switch somewhere to completely disable edge resistance snapping (windows trying to snap to the edge of another window when you drag it past)? it seems right now that is only possible by changing variables in the source and recompiling. or maybe just moving those values to a config file somewhere that can be edited? thanks

**Comment by hiboudev** [comment]
Links of the two PR:
https://github.com/linuxmint/muffin/pull/219
https://github.com/linuxmint/Cinnamon/pull/5099
