### ISSUE TITLE
Customizable click on maximize button

### ISSUE THREAD

**Issue by Massimo-B** [linuxmint/muffin#221]
I would like to see a setting that emulates the behaviour also known on KDE3/4 or Xfce:
Middle-Click on Maximize: Maximize vertically
Right-Click on Maximize: Maximize horizontally
Thanks.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
