### ISSUE TITLE
Closing "not responding / wait or force quit" window kills application

### ISSUE THREAD

**Issue by c0xc** [linuxmint/muffin#222]
This is related to Cinnamon (#4409) but it may be caused by Muffin, so I'm opening this bug here.

When an application window is not responding, Cinnamon will show a popup window "not responding / wait or force quit". Both buttons work as expected, so if the application is just working on something (and not stuck), the user can close the popup by clicking "Wait".
However, closing the popup window (X) will kill the application in question, which is counter-intuitive.

This appears to be a bug, closing the popup shouldn't do anything other than close the popup. The default should be to do nothing.

Those popups appear pretty often (depending on system and workload) and rarely is the affected application really frozen. Closing such a popup window whenever it appears out of the blue (X button or escape key) is easier than finding the "Wait" button.

This may lead to loss of data, or at least some kind of work.

![4d6f9628-50ca-11e5-8c14-28b77c09fff3](https://cloud.githubusercontent.com/assets/7249348/13530583/5b6a2d76-e222-11e5-9576-d8ea34bb869a.png)

How to reproduce:
1. Use Firefox.
2. Firefox will get stuck at some point (temporarily).
3. When Cinnamon's "not responding" popup appears, close it. Firefox will be killed.

**Comment by icarter09** [comment]
Unable to reproduce. There have been several Mint and Firefox versions since this was originally reported.
