### ISSUE TITLE
Wrong context menu positioning in GTK 3.20

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/muffin#224]
After update to gnome 3.19 libs I faced with follow bug. Context menu is always shown in the place of first mouse click.

Steps to reproduce.

1. Open gtk 3 application e.g. gnome terminal.
2. Right click in bottom left. Menu is shown near mouse cursor.
3. Right click in any other area e.g. in top right. Menu is still shown in bottom left.

Context menu in other toolkits (gtk2, qt) is shown in right place. Also I can't reproduce issue in other DE (tested with Gnome, XFCE and KDE 5).

**Comment by vladimir-didenko** [comment]
There is interesting thing. Gtk 3.20.2 fixed problem with context menu but another bug is appeared: all dialog windows (e.g. logout dialog or about dialog) now are raised in top left corner. Not sure if this is bug in muffin or in gtk.

**Comment by vladimir-didenko** [comment]
> all dialog windows (e.g. logout dialog or about dialog) now are raised in top left corner. 

It is known bug in GTK 3.20.2

https://bugzilla.gnome.org/show_bug.cgi?id=764403

Should be fixed in 3.20.3. So it is not bug in muffin so closing issue.

**Comment by vladimir-didenko** [comment]
Sorry guys, but 3.20.3 reintroduce initial problem  (wrong context menu positioning).

**Comment by pierre-guillot** [comment]
Same problem with my archlinux since the last update (I update this computer every 1-2 months) : 
- Cinnamon 2.8.8
- Kernel 4.1.21-1-lts
- gtk2 2.24.30-1
- gtk3 3.20.3-1

**Comment by TurkeyMan** [comment]
Same as above. Fix in the pipe?
