### ISSUE TITLE
Assertion failure when resizing windows

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/muffin#226]
Related to https://github.com/linuxmint/Cinnamon/issues/5182

This seems better placed here, it looks like changes made around commit 748d0e5cd37e5a209bfeabaaa78917fd12b5bb5d have led to a bug which is causing assertion failures in window.c

Right when the crash happens this is the line which goes down: `muffin:ERROR:core/window.c:9877:update_resize: assertion failed: (gravity >= 0)`

This manifests as muffin (or cinnamon) crashing when a new window is opened and is not tiled and then untiled before being moved. It looks like there are a number of other ways you can end up in this situation too (i.e. maximizing a window then restoring it seems to be remove the innoculation).

Stack trace:
https://gist.github.com/wrouesnel/431d175f55aa646dbfe34a8e06f025bc

**Comment by mtwebster** [comment]
I can't reproduce this, if you can, and don't mind building muffin, try this for me:
```
diff --git a/src/core/display.c b/src/core/display.c
index fcb76bd..286942d 100644
--- a/src/core/display.c
+++ b/src/core/display.c
@@ -4920,6 +4920,7 @@ meta_resize_gravity_from_tile_mode (MetaTileMode mode)
         gravity = EastGravity;
         break;
       case META_TILE_TOP:
+      case META_TILE_MAXIMIZE:
         gravity = NorthGravity;
         break;
       case META_TILE_BOTTOM:
```

I'll take your word for it if it fixes things and merge it.  I'm hesitant to blindly do so without being able to test it out and make sure that's what the issue is (though how maximize could be the tile state while resizing, I'm not sure - that bothers me a bit)

Thanks

**Comment by wrouesnel** [comment]
Thanks I'll try it out tonight.

Another specific requirements reproduction is opening the a window, vertically maximizing it by double clicking the border, then attempting to resize horizontally, if that helps. Reproduced with Chrome and gedit.

**Comment by mtwebster** [comment]
Ah cool I can reproduce that, I forgot you had mentioned maximizing partially.

**Comment by mtwebster** [comment]
Ok I'll have to actually fix/implement? resizing while maximized (I've honestly never thought to test this) - did this work in the past?

Handling the maximize tile state prevents a crash, but results in undesirable behavior anyhow.

**Comment by wrouesnel** [comment]
It definitely worked before because it's basically my most common workflow (hence why I originally thought that it was a random crash on a nightly).

**Comment by mtwebster** [comment]
Ah ok

https://xkcd.com/1172/

**Comment by mtwebster** [comment]
Hmm.. looks like it didn't work 100% before, it resizes but becomes no longer 'maximized' anymore, it just becomes *that* size.
