### ISSUE TITLE
Adwaita backup windows theme is not in window settings

### ISSUE THREAD

**Issue by joequant** [linuxmint/muffin#235]
Muffin has a backup windows themes which is not in cinnamon windows settings.  This can be fixed by creating a dummy file in the metacity directory.

[muffin.patch.txt](https://github.com/linuxmint/muffin/files/253337/muffin.patch.txt)

**Comment by zquestz** [comment]
Can confirm this works.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/Cinnamon/issues/4622
