### ISSUE TITLE
"grow" functionality

### ISSUE THREAD

**Issue by jonorthwash** [linuxmint/muffin#247]
Sawfish had some really useful functionality, including window "growing", which is described in depth here:
http://sawfish.tuxfamily.org/sawfish.html/Moving-and-Resizing-Windows.html

In short, in its most basic form, window growing resizes a window to fill all available space between it and an adjacent window, like window maximisation to fill available space.  Sawfish's implementation also allowed for individual edges to be grown independently of the others.

It would be nice to see some functionality like this in mate and cinnamon, in any form.  Ideally there would at least be a keyboard shortcut for 4-edge growing, and there could potentially be an option in window menus.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
