### ISSUE TITLE
"pack" functionality

### ISSUE THREAD

**Issue by jonorthwash** [linuxmint/muffin#248]
Currently muffin supports keyboard shortcuts to move a window to screen edge.  It would be nice if there were something similar that instead moved a window to the edge of the next window in a given direction.  (Depending on number of intervening windows, this would also get it to the screen edge eventually.)  Sawfish supported functionality like this, and called it [window "packing"](http://sawfish.tuxfamily.org/sawfish.html/Moving-and-Resizing-Windows.html).

**Comment by nathan-b** [comment]
KWin (KDE Plasma) supports this as well. It's a surprisingly useful feature, as it provides a key combination that basically says "I want this window to go that way" and lets the window manager figure out how to compose that action without resizing the window (as Muffin's tiling options currently do).

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
