### ISSUE TITLE
Windowed OpenGL applications are not in sync with content

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/muffin#254]
I'm pretty sure that this is not related to Muffin, but I dont know what the cause is and Muffin is the component that is the closest I guess. Check this [video](https://www.youtube.com/watch?v=c32nxfBk4fA). I know there is much more below in the graphics stack but I have no clue how this works together. 

This happens for all windowed OpenGL applications not only chromium.

**Comment by lestcape** [comment]
Yes, I'm development a  javafx application and i can notice this problem to.

**Comment by icarter09** [comment]
@ManuelSchneid3r are you still experiencing this issue?

**Comment by ManuelSchneid3r** [comment]
Unfortunately I cannot check this in the next time, sorry.

**Comment by icarter09** [comment]
@ManuelSchneid3r no worries and thanks for the update.
