### ISSUE TITLE
System76 + mint + DisplayLink DL3900 = kinda works

### ISSUE THREAD

**Issue by MichaelJCole** [linuxmint/muffin#275]
I'm reporting this bug here because I don't know where else.  Feel free to point me in another direction.

I've got a System 76 Kudu laptop with Linux Mint 18 and Cinnamon.  It has an Intell HD 4600 display chip. The goal was to drive 2x external monitors from the laptop.

I attached a [Pluggable "Dual-head MultiDisplay"](https://www.amazon.com/gp/product/B00G5OAT88/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1).  Which uses USB 3.0 and a DisplayLink DL-3900 chip to add extra displays.  

I installed the [official 1.2.65 DisplayLink drivers](http://www.displaylink.com/downloads/ubuntu). 

It works most of the time.  But there are some issues:
  - Configuring the displays through System Settings sometimes freezes (it really didn't like a 1366 by 768 monitor).  ctrl-alt-backspace to relogin will reset.
  - There is a problem with the window manager(?) leaving scraps of app windows when dragging them around.  (see [image](https://plus.google.com/photos/photo/106362772443373541506/6373352436858096306?icm=false)).  It corrects itself after a few seconds.
  - Moving the mouse "flutters" on system menus and title bars, leaving cursor trails similar as image above.  This is most annoying issue.  It also happens on the laptop screen now.
  - [Redshift](http://jonls.dk/redshift/) doesn't work through DisplayPort.  Redshift dims blues at night on the screen at night.
  - The "Rotation" option only shows "normal".  I read this was an existing issue.

Is there a way to resolve some of these issues?  Is it because I'm early on the tech curve, or is there a better way than the driver I downloaded.  The official drivers say Ubuntu 14.04 and 16.04.

I picked Muffin because this seems like a window manager thing...

```
☀  uname -a
Linux mc-desktop 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
☀  cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18
DISTRIB_CODENAME=sarah
DISTRIB_DESCRIPTION="Linux Mint 18 Sarah"

```

See also: https://forums.linuxmint.com/viewtopic.php?f=59&t=237186

**Comment by icarter09** [comment]
@MichaelJCole are you still experiencing this issue on muffin v4.4.2 ?

**Comment by MichaelJCole** [comment]
Dude, this issue was ignored for 2 years - I've way moved on from Mint.  If you want to close it, just close it.
