### ISSUE TITLE
Double-click on Window Menu decoration should close the window

### ISSUE THREAD

**Issue by dg1727** [linuxmint/muffin#278]
Feature request:  A double-click on the window-operations-menu icon (the typical place for this icon is @ left end of titlebar) should be equivalent to clicking the close icon.  

Many users are used to this as a quick way to close windows when the close icon is not visible.  

I didn't see an option similar to this in the "System Settings" > Windows window > Titlebar tab.  

My /usr/bin/cinnamon (lacking the requested feature) is at version 3.2.7.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
