### ISSUE TITLE
Option to use Headerbar theming for titlebars?

### ISSUE THREAD

**Issue by feren** [linuxmint/muffin#279]
Well, I followed this tutorial and ironically, Muffin was decorating like it was on GNOME (Headerbars on Titlebars) afterwards...

On that subject, would there ever be a way to add a little dconf setting that'd make this behaviour enable-able? I can tell from my experience that it works just fine with headerbar-ed titlebars (apart from the few apps that decorate normally, and non-user-level applications that also decorate normally), with the exception of this method causing Nautilus, and so on to not work (but with a bit of work, it should work fine) with the only compromise being the fact GTK then controls the titlebars, could there possibly be a setting? If so, that'll be awesome...

**Comment by JosephMcc** [comment]
What tutorial?

**Comment by feren** [comment]
Ah oops, sorry, I thought I linked to it:
http://askubuntu.com/a/784870/337847

**Comment by feren** [comment]
...also, I replaced "Unity" with "Cinnamon" in the tutorial

**Comment by JosephMcc** [comment]
I don't see this happening. For one it's specific to Ubuntu based distros. Ubuntu patches the gnome apps to work properly with Unity. If you run Cinnamon in another distro such as Debian, Gnome apps that are supposed to display header bars do so properly. There also a good chance you're going to break something else doing this.
