### ISSUE TITLE
Shift click should also grab window focus if focus mode is click

### ISSUE THREAD

**Issue by chaoren** [linuxmint/muffin#291]
```
 * muffin 3.2.1
 * Ubuntu 14.04.5 LTS
 ```

**Issue**
Shift+click doesn't grab window focus (it looks like ctrl-click also has this issue, while alt+click doesn't).

**Steps to reproduce**
1. Set window focus mode to click
2. Focus browser (Chrome in my case)
3. Shift select text from terminal (separate window)
4. Ctrl+Shift+C (to copy selected text from terminal)
5. The Ctrl+Shift+C gets sent to the browser and the developer console pops up
6. Rage

**Expected behaviour**
The shift select text (which starts with a shift+click) should have focused the terminal window, which should then receive my subsequent Ctrl+Shift+C.

**Other information**
Gnome handles this correctly.

**Comment by AlexHaaniWink** [comment]
You're saying that Gnome handles this correctly. But I found this issue because for me Gnome (now 3.22.2 in Debian 9) does behave exactly like in your reproduction steps.

**Comment by chaoren** [comment]
Just happened to me again today.

> You're saying that Gnome handles this correctly. But I found this issue because for me Gnome (now 3.22.2 in Debian 9) does behave exactly like in your reproduction steps.

Sorry, I haven't used gnome in years. Original report may have been inaccurate, or only applied to whatever version of gnome I was using at the time.

So I did some more testing just today, and my original report seems to be inaccurate at least as of muffin 3.8.2-1.
- The modifiers (shift, ctrl, alt) either all or none work for focus clicking (alt isn't special).
- On some applications (e.g., Chrome, IntelliJ), clicking with a modifier anywhere in the window does grab focus as expected.
- On applications (e.g., Gnome Terminal, Nemo) that don't grab focus when clicked with a modifier, clicking with a modifier on the title bar seems to always still grab focus as expected.

So this leads to me to think that this might not be a problem with muffin. Maybe it's a problem with the group of applications that does something stupid with modifier clicks when it happens in the body of the window. E.g., Gnome Terminal probably just handled shift-click for selecting text, then threw away the click before it can be propagated to handle window focus.

**Comment by AlexHaaniWink** [comment]
> So this leads to me to think that this might not be a problem with muffin. Maybe it's a problem with the group of applications that does something stupid with modifier clicks when it happens in the body of the window. E.g., Gnome Terminal probably just handled shift-click for selecting text, then threw away the click before it can be propagated to handle window focus.

That could very well be in the right direction. But I have no idea where to report something as generic as this. I could perhaps create an issue for the programs that specifically cause an issue for me. In my case Thunderbird.

I only found this issue here in this muffin Github project (which I don't use, nor linuxmint) because I have this exact same issue. Just with different tools.

**Comment by chaoren** [comment]
Did a little debugging with the VTE project (the terminal part of gnome terminal), and it looks like the focus_in_event just never fires for the GTK widget when modifier keys are held, even though it still receives the button_press_event. I'm guessing every affect application is built with GTK, and this is the default behavior. I'll file a bug with GTK and see if they can do anything.

**Comment by chaoren** [comment]
https://gitlab.gnome.org/GNOME/gtk/issues/2382
