### ISSUE TITLE
Covering GTK3 apps

### ISSUE THREAD

**Issue by oksoft-ondra** [linuxmint/muffin#295]
```
 * muffin version (muffin --version or 'dpkg --list | grep libmuffin0' for Mint/Ubuntu)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

Muffin 3.4.0-1 Archlinux 64Bit.
**Issue**
If I Tile on top a GNOME-styled GTK3 app, it covers part of windows title on 2560x1600.
Please improve it.

**Comment by JosephMcc** [comment]
This report is on an older version of Muffin and probably needs a screenshot or something to better understand the problem.
