### ISSUE TITLE
gtkdoc fatal error in build process of 3.4.1

### ISSUE THREAD

**Issue by ng-0** [linuxmint/muffin#296]
While working on getting Cinnamon into Guix and GuixSD, I get this while building
muffin with our internal "glib-ok-gtk-build-system":

```
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/(.*?){ <-- HERE / at /gnu/store/gck033wg21w0j3lb7kz68nzan3nnizpv-gtk-doc-1.25/bin/gtkdoc-scan line 735.
```

What I found is https://unix.stackexchange.com/questions/238539/automake-error-unescaped-left-brace-in-regex-is-deprecated and https://bugs.archlinux.org/task/52676 for this issue.
Do you have an idea how to get past this issue?
It happens at the end of the build process, which is annoying.

**Comment by leigh123linux** [comment]
You need to fix intltool.

http://pkgs.fedoraproject.org/cgit/rpms/intltool.git/commit/?id=f38d92c429e3360d2963ffe59ed82fa5be9a7724
