### ISSUE TITLE
Cannot Go Fully Fullscreen With Cheese

### ISSUE THREAD

**Issue by SerafDosSantos** [linuxmint/muffin#300]
```
 * muffin version: 3.4.1+sonya
 * Distribution: Mint 18.2
 * 64 bit
 ```

**Issue**

Although I select Fullscreen on Cheese, I always have the menu displayed on top. The webcam view does not display fullscreen as it should. Fullscreen works on Ubuntu 17.04. Problem existent on previous versions of Mint.

**Steps to reproduce**

Go fullscreen through the menu.

**Expected behaviour**

To have a fullscreen view of the webcam.

**Comment by JosephMcc** [comment]
Don't think this is a muffin issue. Cheese relies on the `gtk-dialogs-use-header` to determine if it should show a header bar or not. In Cinnamon it does not which results in that menubar. Though I didn't look this is quite possible compounded by Unity specific patches that Ubuntu makes to many of these apps to get them working properly in their desktop environment.
