### ISSUE TITLE
Window animations on 2d grid are in wrong direction

### ISSUE THREAD

**Issue by gunsch** [linuxmint/muffin#302]
```
 * muffin version (muffin --version or 'dpkg --list | grep libmuffin0' for Mint/Ubuntu)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

muffin version: muffin 3.2.1
Distribution: Debian GNU/Linux rodete (Google internal build)
`lspci | grep -i vga`: VGA compatible controller: NVIDIA Corporation GM107GL [Quadro K620] (rev a2)
64-bit

**Issue**
Window animation moves in incorrect direction when switching workspaces in a 2d grid.

Prerequisites:
* Window Effects are enabled
* Using the Cinnamon applet [`workspace-grid@hernejj`](https://github.com/hernejj/workspace-grid-cinnamon-applet/tree/master/workspace-grid%40hernejj) (seems to be the de-facto applet for this functionality)

**Steps to reproduce**

* Set up workspaces as 2d grid with >1 row of workspaces. (I use 3x3).
* Use the "Ctrl+alt+down" and "Ctrl+alt+up" 
* Ctrl+alt+down animation moves "down and to the left", and Ctrl+alt+up animation moves "up and to the left".

**Expected behaviour**
Down/up animations move directly down and up.

**Other information**
Others have reported this bug publicly, but not in muffin, e.g. on the [workspace applet](https://github.com/hernejj/workspace-grid-cinnamon-applet/issues/19), but from some initial investigation I believe the problem is in muffin's code.

1. The applet (Cinnamon JS applet) simply calls `Main.wm.actionMoveWorkspaceDown` and `Main.wm.actionMoveWorkspaceUp`, where `Main` is `imports.ui.main`.
1. `main.js` has the following definitions:
    ```
    actionMoveWorkspaceUp: function() {
        global.screen.get_active_workspace().get_neighbor(Meta.MotionDirection.UP).activate(global.get_current_time());
    },
    actionMoveWorkspaceDown: function() {
        global.screen.get_active_workspace().get_neighbor(Meta.MotionDirection.DOWN).activate(global.get_current_time());
    },```
1. This calls into `meta_workspace_activate`, which falls into `get_wrapped_horizontal_direction` to determine an initial left-right direction. I believe it's failing [here](https://github.com/linuxmint/muffin/blob/a49dc2864fd01183ada2f2d849a432818fd62c84/src/core/workspace.c#L567) by always falling into the "LEFT" case when `from == to`.

**Comment by jonorthwash** [comment]
It might help to mention that the behaviour was not like this prior to Cinnamon 3.0 or so—that is, the expected behaviour used to be obtained.
