### ISSUE TITLE
Request: Individual Interface Scaling Per Monitor

### ISSUE THREAD

**Issue by lehitoskin** [linuxmint/muffin#304]
(This is a repost from the Cinnamon issue I created, since I wasn't sure where to put it at first.)

```
 * muffin version (muffin --version or 'dpkg --list | grep libmuffin0' for Mint/Ubuntu) 3.4.1
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Gentoo
 * Graphics hardware *and* driver used
  - GTX 1080 Ti
  - nvidia-drivers-387.22
 * 32 or 64 bit - 64-bit
 ```

**Issue**
I have one 4K monitor as my main display and a 1080p monitor as my secondary. When I set the user interface scaling to 2x (Hi-DPI), everything on the 1080p monitor is outrageously ballooned. If I set the scaling to normal, everything on the 4K monitor is far too tiny to see. This would be alleviated if there was a way to set the user interface scaling per display, as is possible in Windows.

With such a change, it may be prudent to relocate the user interface scaling from General to Display, which would associate interface scaling to the per-monitor idea more easily.

**Comment by JosephMcc** [comment]
We already have a large issue open for this on Cinnamon. In short it isn't really possible without Wayland support.

**Comment by lehitoskin** [comment]
You mean to say that this isn't possible under X, but it is in Wayland?

Also, it's pretty funny you mention the Cinnamon repository because I posted this issue over there and it was closed and I was told to post it under Muffin.

**Comment by JosephMcc** [comment]
It's supposed to be possible under Wayland. I've not tried it but I believe gnome3.26 either supports it or had it as an experimental feature.
