### ISSUE TITLE
Widening Gnome-terminal corrupts desktop screen

### ISSUE THREAD

**Issue by penttila** [linuxmint/muffin#305]
1) Pull the right edge of gnome-terminal to an 'extreme' length by the mouse
2) When its size extends the 251 width a kind of 'shadow' frame appears around the window's normal frame which corrupts the desktop screen!
3) This always happens and 'undo-able' by decreasing the window size

(I also reported this bug on Launchpad as #1737888)
![screenshot](https://user-images.githubusercontent.com/8037522/33929234-0aee35a6-dfe9-11e7-8a2a-735ece4d0e65.png)

Technical details:

xxx@afo ~ $ dpkg --list | grep libmuffin0
ii  libmuffin0   3.6.0+sylvia   amd64  window and compositing manager (shared library)

Gnome-terminal: 3.18.3

System: Host: afo Kernel: 4.10.0-42-generic x86_64 (64 bit gcc: 5.4.0)
Desktop: Cinnamon 3.6.6 (Gtk 2.24.30) dm: mdm Distro: Linux Mint 18.3 Sylvia
Machine: Mobo: Gigabyte model: G31M-ES2L v: x.x Bios: Award v: FG date: 02/24/2010
CPU: Dual core Pentium E5500 (-MCP-) cache: 2048 KB
flags: (lm nx sse sse2 sse3 ssse3 vmx) bmips: 11200
clock speeds: min/max: 1200/2800 MHz 1: 1200 MHz 2: 1200 MHz
Graphics: Card: Intel 82G33/G31 Express Integrated Graphics Controller
bus-ID: 00:02.0 chip-ID: 8086:29c2
Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa)
Resolution: 1280x1024@60.02hz
GLX Renderer: Mesa DRI Intel G33 GLX Version: 1.4 Mesa 17.0.7 Direct Rendering: Yes

**Comment by JosephMcc** [comment]
This isn't a bug. Its a hard coded texture size limitation. At 250 columns the terminal is over 2000px wide. That means your window is 2x as wide as your monitor. In practical real use this isn't an issue you will ever encounter and prevents crashing when some apps (chrome is an offender if I remember correctly) request obscene texture sizes.

**Comment by penttila** [comment]
I am creating a .deb package in this terminal with debhelper which creates very long line outputs. This is the reason why I wanted to have a 'very wide' window, this is my practical real use case.

I would suggest:
   1) increase this limit to somewhat higher
   2) do not mark the acceding of this limit by corrupting the screen, just do not let it be extended any more

Thanks for your quick response.

**Comment by clefebvre** [comment]
Why not just pipe your output into a file and study it in a text editor?

**Comment by penttila** [comment]
Yes, you are right.  The output can be redirected into a file.
On the other hand the natural way of creating a .deb package is using shell scripts and makefiles in a terminal. I am struggling with porting a Windows application to linux and my whole 'build' environment is here. I have to make all kind of tricks to make it running somehow, so it is very nice to see in 'real-time' if I make a mistake somewhere.
