### ISSUE TITLE
Full screen window will always be foreground even alt-tab to other window

### ISSUE THREAD

**Issue by adam900710** [linuxmint/muffin#316]
```
 * muffin 3.8.0
 * Arch
 * Geforce 1060, proprietary driver
 * 64 bit
 ```

For real full screen window (sakura/gnome-terminal F11), it will always keep foreground.
And since the termial is always in foreground, it's impossible to properly switch to other window.

**Steps to reproduce**
1. Run sakura (with background transparency)
2. Press F11 to make it full screen
3. Alt-tab to other window

**Expected behaviour**
Window switched to will be foreground, other than the full scren sakura.

**Other information**
The problem is a regression as muffin 3.6 doesn't have this problem.

**Comment by itzexor** [comment]
This seems to be caused by https://github.com/linuxmint/muffin/commit/97faaee79b07c4a9ac436cc1dbf5182f05374c27

**Comment by itzexor** [comment]
This should be fixed in the next point release
