### ISSUE TITLE
Wrong Z-order by XReconfigureWMWindow() call

### ISSUE THREAD

**Issue by mse2** [linuxmint/muffin#327]
Mint Cinnamon 18.2
While adapting MSEide+MSEgui
https://sourceforge.net/projects/mseide-msegui/
to Mint I found that in XReconfigureWMWindow() call stackmode "Below" windows are placed at the bottom of the window stack instead just below the sibling, see the attached test programs.
https://tronche.com/gui/x/xlib/window/configure.html#XWindowChanges
"
If a sibling and a stack_mode are specified, the window is restacked as follows:

Above The window is placed just above the sibling.
Below The window is placed just below the sibling.
"
[zorder.zip](https://github.com/linuxmint/muffin/files/2096934/zorder.zip)
[zorder1.zip](https://github.com/linuxmint/muffin/files/2096936/zorder1.zip)

**Comment by mse2** [comment]
Before you close and lock the issue please read it. There are testprograms which demsonstrate the problems.

**Comment by leigh123linux** [comment]
I'm getting sick of your non descriptive issues.
