### ISSUE TITLE
Gsettings option to remove decorations from maximized windows

### ISSUE THREAD

**Issue by memeplex** [linuxmint/muffin#328]
```
~:: uname -a
Linux carlos 4.14.52-1-MANJARO #1 SMP PREEMPT Tue Jun 26 15:24:31 UTC 2018 x86_64 GNU/Linux

~:: cinnamon --version
Cinnamon 3.8.6

~:: lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)

~:: pacman -Qs xf86-video-intel
local/xf86-video-intel 1:2.99.917+829+gd7dfab62-1 (xorg-drivers)
    X.org Intel i810/i830/i915/945G/G965+ video drivers
```

I've asked for this in a [comment](https://github.com/linuxmint/Cinnamon/issues/7681#issuecomment-402025003) but since it's a related but independent issue I'm opening a new request.

The ability to remove decorations of maximized windows (kinda fullscreen but with a visible panel) is pretty much demanded:

1. Popular "maximus style" extensions exist both for Gnome and Cinnamon, although horribly hackish, using external tools, hooking from all kind of events, sometimes inferring a client id from window's title.

2. Alternative hacks like tweaking the metacity theme to reduce maximized title bars pop up every once in a while in reddit, stackoverflow, etc.

3. Many other DEs and WMs offer an equivalent inbuilt feature: mate, plasma, xfce, openbox.

Now, I understand it can be a dangerous option for the novice since losing decorations means losing visual/mouse control over the window. So what I'm requesting is a **gsettings option, pretty much hidden from everything but a dconf editor**, that requires consciously googling, reading documentation, finding the adequate property and deliberately toggling it. I assume this also makes the implementation much simpler because no fancy UI is needed.

Notice that this is not the same as supporting _GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED since what I'm requesting is a WM-level toggle, not an app-level one that requires to hopefully wait that the client eventually adds a "zen mode" option or whatever.

I believe this request is in the spirit that differentiates Cinnamon from Gnome by giving the user more power and a more traditional experience (I call this feature traditional because it was more common a decade ago than it is now).

**Comment by leigh123linux** [comment]
This should be set by the client window not muffin.

**Comment by memeplex** [comment]
Just out of curiosity, if you can take a little time to elaborate, why are you so adamantly opposed to this feature? I've presented some arguments for it and suggested a "user-proof" way to provide it. Have you already fully jumped on the CSD bandwagon?

**Comment by JosephMcc** [comment]
Weather we or anyone else likes csd windows, they are a simple reality. They aren't going anywhere. That means a setting that will produce inconsistent results. We already get enough complaints about things like window border themes not affecting all windows.

We also aren't normally in the habit of doing these types of "hidden" settings. If it isn't going to work well enough, or we don't feel there is good reason for it, then we typically don't add it. We get a lot of requests to just add a setting for this or that. Every setting adds more complexity to things. Just not sure it's worth it for this.

**Comment by memeplex** [comment]
Ok, thank you very much for the explanation. I'm going to try build a simple utility using xlib or pyxlib in order to implement some kind of rules. Maybe something like that already exists.

**Comment by memeplex** [comment]
Just for anyone that happens to end up here in the future:

```python
#!/usr/bin/python

import os, time

from Xlib import display, X, error, protocol, Xatom

disp = display.Display()
root = disp.screen().root
hide_atom = disp.intern_atom('_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED')
type_atom = disp.intern_atom('_NET_WM_WINDOW_TYPE')
normal_atom = disp.intern_atom('_NET_WM_WINDOW_TYPE_NORMAL')
root.change_attributes(event_mask=X.SubstructureNotifyMask)
while True:
    event = disp.next_event()
    if event.type == X.CreateNotify:
        win = event.window
        try:
            type = win.get_full_property(type_atom, X.AnyPropertyType)
        except error.BadWindow:        
            continue
        if type and type.value[0] == normal_atom:
            time.sleep(0.1)
            win.change_property(hide_atom, Xatom.ATOM, 32, [1])
```

I still don't understand why the sleeping part is necessary though.
