### ISSUE TITLE
How do I safely upgrade my debian stretch to muffin 3.4 or newer?

### ISSUE THREAD

**Issue by drandreaskrueger** [linuxmint/muffin#364]
I have a huge `.xsession-errors`, which keeps on growing by the second, with lines like

```
warning: Log level 8: meta_screen_get_monitor_geometry: assertion 'monitor >= 0
&& monitor < screen->n_monitor_infos' failed
```

I found this https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877026 which says

```
Date: Thu, 28 Sep 2017 11:37:17 +0200
control: reassign -1 muffin 3.2.1-2   fixed -1 3.4.0-1

this bug is related to muffin and already solved in 3.4
```

So my only open question is: 

**How do I safely upgrade my debian stretch to muffin 3.4 or newer?**

Thanks a lot!

--------------

* muffin version (muffin --version or 'dpkg --list | grep libmuffin0' for Mint/Ubuntu)

```
muffin --version
muffin 3.2.1

dpkg --list | grep libmuffin0
ii  libmuffin0                                                       3.2.1-2                                     amd64        lightweight window and compositing manager (shared library)
```

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)

Debian stretch

```
uname -a
Linux .... 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux
```

 * Graphics hardware *and* driver used

?

 * 32 or 64 bit

64 bit

**Comment by jaszhix** [comment]
Debian doesn't include anything newer than mozjs24, which Cinnamon 3.4 needs to work correctly. You could try LMDE 3, it is based on Stretch and includes Cinnamon 3.8.

**Comment by leigh123linux** [comment]
This should be report to debian bug tracker.
