### ISSUE TITLE
Mutter source installation failure, no compile

### ISSUE THREAD

**Issue by kimariterikishi** [linuxmint/muffin#375]
```
 * muffin version: https://github.com/linuxmint/muffin
 * Distribution - (Linux Mint 19 Tara v2 | Cinnamon)
 * Graphics hardware *and* driver used: Intel / Virtualbox
 * 64 bit
 ```

**Issue**

Hi

Problem a Muffin Git in Linux Mint 19 Tara, Cinnamon (Virtualbox).
When I tried a Cinnamon 4.0.0 version, its dependence on Mutter ... .

The solutions doesn't work
https://community.linuxmint.com/tutorial/view/955
... > dpkg-buildpackage
or the traditional
... > ./configure ; make ; sudo make install

...
./.libs/libmuffin-clutter-0.so: undefined reference to `cogl_wayland_display_set_compositor_display'

./.libs/libmuffin-clutter-0.so: undefined reference to `cogl_wayland_texture_2d_new_from_buffer'

collect2: error: ld returned 1 exit status
linking of temporary binary failed: Command '['/bin/bash', '../libtool', '--mode=link', '--tag=CC', '--silent', 'gcc', '-o', '/home/lm19v2cinn/muffin/clutter/clutter/tmp-introspectqtzf30en/Clutter-0', '-export-dynamic', '-g', '-O2', '/home/lm19v2cinn/muffin/clutter/clutter/tmp-introspectqtzf30en/Clutter-0.o', '-L.', 'libmuffin-clutter-0.la', '-lgio-2.0', '-lgobject-2.0', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-lglib-2.0']' returned non-zero exit status 1.
/usr/share/gobject-introspection-1.0/Makefile.introspection:159: recipe for target 'Clutter-0.gir' failed
make[4]: *** [Clutter-0.gir] Error 1
make[4]: Leaving directory '/home/lm19v2cinn/muffin/clutter/clutter'
Makefile:1429: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/lm19v2cinn/muffin/clutter/clutter'
Makefile:476: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/lm19v2cinn/muffin/clutter'
Makefile:496: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/lm19v2cinn/muffin'
Makefile:428: recipe for target 'all' failed
make: *** [all] Error 2

**Other information**
Virtualbox

**Comment by leigh123linux** [comment]
TBH your inability to compile code isn't our issue.

See rules file for the required extra configure options.

https://github.com/linuxmint/muffin/blob/master/debian/rules#L33

**Comment by kimariterikishi** [comment]
Thanks for the quick answer as I have time, I watch. yesterday was a very sleepy time when I read (at dawn).

**Comment by clefebvre** [comment]
You need to build/install both muffin and cinnamon 4.0.0 (and the other cinnamon components).

Alternatively, you can download the CI debs for Mint 19:

```
TARGET="mint19"

mkdir -p cinnamon-packages
rm -rf cinnamon-packages/*
cd cinnamon-packages
wget https://github.com/linuxmint/xapps/releases/download/master.${TARGET}/packages.tar.gz -O xapps.tar.gz
wget https://github.com/linuxmint/cjs/releases/download/master.${TARGET}/packages.tar.gz -O cjs.tar.gz
wget https://github.com/linuxmint/cinnamon-translations/releases/download/master.${TARGET}/packages.tar.gz -O cinnamon-translations.tar.gz
wget https://github.com/linuxmint/cinnamon-desktop/releases/download/master.${TARGET}/packages.tar.gz -O cinnamon-desktop.tar.gz
wget https://github.com/linuxmint/cinnamon-menus/releases/download/master.${TARGET}/packages.tar.gz -O cinnamon-menus.tar.gz
wget https://github.com/linuxmint/cinnamon-session/releases/download/master.${TARGET}/packages.tar.gz -O cinnamon-session.tar.gz
wget https://github.com/linuxmint/cinnamon-settings-daemon/releases/download/master.${TARGET}/packages.tar.gz -O cinnamon-settings-daemon.tar.gz
wget https://github.com/linuxmint/cinnamon-control-center/releases/download/master.${TARGET}/packages.tar.gz -O cinnamon-control-center.tar.gz
wget https://github.com/linuxmint/cinnamon-screensaver/releases/download/master.${TARGET}/packages.tar.gz -O cinnamon-screensaver.tar.gz
wget https://github.com/linuxmint/muffin/releases/download/master.${TARGET}/packages.tar.gz -O muffin.tar.gz
wget https://github.com/linuxmint/nemo/releases/download/master.${TARGET}/packages.tar.gz -O nemo.tar.gz
wget https://github.com/linuxmint/cinnamon/releases/download/master.${TARGET}/packages.tar.gz -O cinnamon.tar.gz
ls *.tar.gz | xargs -i tar zxvf {}
#echo "APT::Cache-start 200000000;" > /etc/apt/apt.conf.d/00fixaptsegfaults
sudo apt install --yes --allow-downgrades ./packages/*.deb
#rm -rf packages
```

**Comment by kimariterikishi** [comment]
> TBH your inability to compile code isn't our issue.
> 
> See rules file for the required extra configure options.
> 
> https://github.com/linuxmint/muffin/blob/master/debian/rules#L33

Not good.

sudo make clean

./configure --disable-wayland-egl-platfo

and

make

finished same:

 CCLD     libmuffin-clutter-0.la
  GISCAN   Clutter-0.gir
./.libs/libmuffin-clutter-0.so: undefined reference to `cogl_wayland_display_set_compositor_display'
./.libs/libmuffin-clutter-0.so: undefined reference to `cogl_wayland_texture_2d_new_from_buffer'
collect2: error: ld returned 1 exit status
linking of temporary binary failed: Command '['/bin/bash', '../libtool', '--mode=link', '--tag=CC', '--silent', 'gcc', '-o', '/home/lm19v2cinn/muffin/clutter/clutter/tmp-introspectg7oo9lw1/Clutter-0', '-export-dynamic', '-g', '-O2', '/home/lm19v2cinn/muffin/clutter/clutter/tmp-introspectg7oo9lw1/Clutter-0.o', '-L.', 'libmuffin-clutter-0.la', '-lgio-2.0', '-lgobject-2.0', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-lglib-2.0']' returned non-zero exit status 1.
/usr/share/gobject-introspection-1.0/Makefile.introspection:159: recipe for target 'Clutter-0.gir' failed
make[4]: *** [Clutter-0.gir] Error 1
make[4]: Leaving directory '/home/lm19v2cinn/muffin/clutter/clutter'
Makefile:1429: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/lm19v2cinn/muffin/clutter/clutter'
Makefile:476: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/lm19v2cinn/muffin/clutter'
Makefile:496: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/lm19v2cinn/muffin'
Makefile:428: recipe for target 'all' failed
make: *** [all] Error 2
lm19v2cinn@lm19v2cinn-VirtualBox:~/muffin$
