### ISSUE TITLE
Horrible window artifacting with muffin and cinnamon

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/muffin#378]
```
 * muffin version (muffin --version or 'dpkg --list | grep libmuffin0' for Mint/Ubuntu)
muffin 4.0.0-1
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch
 * Graphics hardware *and* driver used
Nvidia 410.66
 * 32 or 64 bit
64-bit
 ```

**Issue**
After upgrading to new muffin and new cinnamon (4.0.0) I'm experiencing a massive amount of screen artifacts. Whenever I move a window, portions of old ones remain on the screen. And they remain on the screen for a very long time (or until you click somewhere on the background screen). Needless to say, this is extremely annoying and has forced me to downgrade.

**Steps to reproduce**
Install new muffin + cinnamon.

![screenshot from 2018-11-12 12-08-24](https://user-images.githubusercontent.com/7957590/48363716-7a8bbe80-e69e-11e8-9650-d0bc50fece71.jpg)

**Comment by clefebvre** [comment]
are you setting any CLUTTER env variables?

**Comment by nick-s-b** [comment]
Clement, I believe so. I have: `CLUTTER_PAINT=disable-clipped-redraws:disable-culling`
This was recommended somewhere long time ago. Is this the culprit?

**Comment by nick-s-b** [comment]
Okay! Removing these two fixed it. No more redraw issues. I'm not sure if `CLUTTER_VBLANK=True` is also necessary anymore but I can confirm that without either of them, the issues are gone.
Given how these settings were popular and recommended at some point in time, I'm sure others will also have this issue. Maybe it would be wise to ignore it in muffin? Anyway, thank you so much @clefebvre !

**Comment by jaszhix** [comment]
@clefebvre Cinnamon sets CLUTTER_PAINT itself when in software rendering mode, so before we do we need to figure out a way to manage that variable internally.
