### ISSUE TITLE
Muffin 4: Window decorator artifacts when in the full-screen mode with mpv

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/muffin#380]
```
 * muffin version (muffin --version or 'dpkg --list | grep libmuffin0' for Mint/Ubuntu)
muffin 4.0.1-1
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch
 * Graphics hardware *and* driver used
Nvidia 410.73
 * 32 or 64 bit
64bit
 ```

**Issue**
I've noticed that when I watch videos with `mpv` in the full-screen mode, there are screen artifacts at the top left side of the screen. I've recompiled the `mpv` just to make sure it's not the cause of it (I'm using the latest git version) but the artifacts are still there.

Artifacts are always of the similar shape (square with the circle cut out) and they're exactly the width of the `mpv` window chrome apart. They seem to be the alpha channel of the window chrome. My windows are slightly rounded so I guess `muffin` is somehow rendering those in for some reason. And they are all positioned in the top left corner.
Really strange... never came across a bug like this before.
There are no artifacts in the normal, windowed, mode.

My mpv window (notice the rounded edges of this theme): https://i.imgur.com/dP4Qube.jpg

Images (4K) showing artifacts when in full-screen mode:
In this first image you can clearly see that the artifacts look like the alpha channel of window chrome:
https://i.imgur.com/MtvfHMW.jpg
https://i.imgur.com/VewJj74.jpg

**Steps to reproduce**
Run mpv in full-screen.

**Comment by jaszhix** [comment]
What version of MPV is this? Can you paste the output of `mpv -v` including the versions?

Mine is:

```
[cplayer] mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.78.100
[cplayer]    libavcodec      57.107.100
[cplayer]    libavformat     57.83.100
[cplayer]    libswscale      4.8.100
[cplayer]    libavfilter     6.107.100
[cplayer]    libswresample   2.9.100
[cplayer] ffmpeg version: 3.4.4-0ubuntu0.18.04.1
```

I'm not able to reproduce this in either mpv from CLI or gnome-mpv, after resizing the window and switching to fullscreen, and when maximizing. This is very similar to an artifact I fixed when maximizing framed windows, and I suspect a similar fix could work for this as well when a window is fullscreen or tiled. 

I still can't reproduce it when switching to a light theme with rounded corners, though. Knowing which theme you're using might make it easier to reproduce.

Here's a sample clip I tested in 4K - http://downloads.4ksamples.com/downloads/sample-Elysium.2013.2160p.mkv

**Comment by nick-s-b** [comment]
Hi, version is:

````
mpv 0.29.0-92-gb222980394 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.23.101
   libavcodec      58.39.100
   libavformat     58.22.100
   libswscale      5.4.100
   libavfilter     7.43.100
   libswresample   3.4.100
ffmpeg version: N-92434-g2f888771cd
````
It's basically the latest version of mpv. I just tried it with Cinnamon project's `xplayer`. Exact same thing happens so we can eliminate the possibility that it's `mpv` (and it also happens with VLC which makes it highly unlikely that's the fault of any of them):

xplayer: https://i.imgur.com/MBEjWs6.jpg
vlc: https://i.imgur.com/XKD131M.jpg

You can see the alpha channel as white triangles at the top=left and the top-middle of the screen (it's a 1080p movie so it's in the middle).

Instead of looking at the 4K footage (like from your clip), it's much easier to see it in sized 720p/1080p (or less) clips because the top of the right window is then in near the middle of the screen. When I tried playing your clip, I saw it in the top left corner only.

I'm using an Arc-based theme that I fixed and modified some time back. I haven't shared it or uploaded it anywhere but here it is:

https://www.dropbox.com/s/r66r0n9wtlsc8ps/Arc-Flat-Fixed.tar.xz?dl=0

You can drop it into `/usr/share/themes` of course... runded corners come from CSS in `metacity`... you know all that better than me :smile:

**Comment by leigh123linux** [comment]
It works fine here using mint-y-dark theme

![screenshot from 2018-11-14 15-31-21](https://user-images.githubusercontent.com/1299302/48492822-8902e300-e822-11e8-90c1-1edd2921a1c6.png)
```
$ mpv -V
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1
```

```
$ inxi -GS
System:
  Host: leigh.computer-desktop Kernel: 4.18.17-300.fc29.x86_64 x86_64 
  bits: 64 Desktop: Cinnamon 4.0.1 Distro: Fedora release 29 (Twenty Nine) 
Graphics:
  Device-1: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 415.13 
  Display: x11 server: Fedora Project X.org 1.20.3 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 3840x2160~60Hz 
  OpenGL: renderer: GeForce GTX 1050 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 415.13
```

**Comment by nick-s-b** [comment]
@leigh123linux it's not an `mpv` issue. It happens with other players too. It's an issue with how `muffin` handles window chrome and transparency.

**Comment by nick-s-b** [comment]
I can confirm that it's been fixed. Thank you so much @jaszhix !
