### ISSUE TITLE
Xpad window border glitch when window decorations are enabled.

### ISSUE THREAD

**Issue by smurphos** [linuxmint/muffin#388]
```
 * muffin version 4.02
 * Distribution - Manjaro testing 
 * Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
  vendor: Hewlett-Packard driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.20.3 driver: modesetting tty: N/A 
  OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 18.2.5 
  direct render: Yes 
 * 64 bit
 ```
On launching xpad and enabling window decorations in xpad settings there is a anomalous box shadow shape frame around the window. It can be fixed by resizing the xpad slightly. In Manjaro this frame appears to include elements from the xpad settings window. 

Repeatedly toggling window decorations in xpad on and off can sometimes cause a cinnamon crash. I'll see if I can get some more info on that one.

Also reproduced this behaviour in Mint 19 + Cinnamon 4.02 from unofficial PPA running in virtualbox. The only difference is the anomalous frame is black.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by jaszhix** [comment]
Installed xpad, not seeing anything unusual when toggling the window decorations initially. When you add more notes, and toggle the setting, it will re-show notes that were previously opened. Then if you delete the note and toggle the setting, it shows empty windows where the deleted notes used to be. Lots of warnings. No crashes for me.

```
Cinnamon warning: Log level 16: STACK_OP_LOWER_BELOW: window 0x6c046a5 not in stack
Cinnamon warning: Log level 16: STACK_OP_LOWER_BELOW: sibling window 0x6c046a5 not in stack
```

This behavior is unchanged in Mate, so I'm tempted to say this isn't a Muffin bug.

**Comment by smurphos** [comment]
I can reliably crash cinnamon by turning xpad window decorations on and then off again in both Manjaro and my virtualbox Mint 19 + Cinnamon PPA  where I can't with Cinnamon 3.8. This is from the virtualbox machine. Virtualbox is running on a regular mint 19 host. 

```muffin --version
muffin 4.0.3
cinnamon --version
Cinnamon 4.0.3
xpad --version
Xpad 5.0
```

Crash report from mint-reports
[crash.tar.gz](https://github.com/linuxmint/muffin/files/2623261/crash.tar.gz)
http://termbin.com/55tz

**Comment by jaszhix** [comment]
OK, I can't reproduce the crash on Nvidia or Intel on the optimus laptop, but could in vmware, and #389 fixes it for me. Can you verify?

https://drive.google.com/open?id=1xvlN5B3GSaBaGFVBBHh7afjUYcfm3i8V

**Comment by smurphos** [comment]
Yep that prevents the crash in the virtualbox machine. Still get the weird outline on first enabling window decorations but a resize or minimising to the tray and reopening gets rid of that.

**Comment by jaszhix** [comment]
Ok, I'll try to fix the artifact. It turns out window effects being disabled prevents this from occurring. I could reproduce the crash on my main machine after enabling them.

**Comment by jaszhix** [comment]
@smurphos Didn't get anywhere in muffin, but the cinnamon PR referenced here should fix the artifacts until I have more time find a better fix.

There's more that can be experimented with, but I'm not comfortable with changing a lot of existing code in a point release for one app.
