### ISSUE TITLE
"Disable compositing for full-screen windows" not working on wine fullscreen games

### ISSUE THREAD

**Issue by jaszhix** [linuxmint/muffin#400]
Moved from linuxmint/Cinnamon#8153, @str225 wrote: 
#
```
 * Cinnamon version: Cinnamon 4.0.5
 * Distribution: Manjaro
 * Graphics hardware *and* driver used: i915 intel graphics hd 620
 * 64 bit
```
[.xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2687634/xsession-errors.txt)

**Issue**
With "Disable compositing for full-screen windows" option enabled: The option is working fine on native linux games, but the compositor is not being disabled on fullscreen wine games unless i enable a virtual desktop on wine. I could guess that the compositor was not disabled because the gameplay was really choppy on osu!, and i didn't have this issue on other DEs that have a similar option like gnome and budgie.

**Comment by awsms** [comment]
was the patch for wine implemented?

**Comment by leigh123linux** [comment]
Start a new issue if it's still relevant.
