### ISSUE TITLE
Virtualbox seamless mode with LM19.1 

### ISSUE THREAD

**Issue by Andy2051** [linuxmint/muffin#404]
```
 * muffin version 3.8.2
 * Distribution - mint 19.1 cinnamon
 * inxi -G output
           Intel 3rd Gen Core processor Graphics Controller
           Display Server: x11 (X.Org 1.19.6 )
           drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 2560x1080@60.00hz
           OpenGL: renderer: Mesa DRI Intel Ivybridge Mobile

 * 64 bit
 ```

LM19.0 plus virtualbox work fine in seamless mode, this with either VB5.2.22 or VB6.0 (with extn packs and guest additions at same version). Upgrading to LM19.1 and seamless doesn't work. Tried on two different PCs, thinkpad T430 and homebuilt desktop with i5-8400 + gtx1080 = same result on both. LM host and win7 guest.

The problem appears to be graphics related. The windows taskbar will appear above the mint panel, but the windows start menu will not appear. Any win apps launched appear to launch but nothing shows in the display. The VB control panel has to be started to to kill the win7 session. In addition, in seamless the VB menu is a 'drop down' at the top of the screen, there is a ragged grey box where this menu should appear.

If VB is started in full screen mode, there is no problem. However, switching to seamless causes the problem above.

This has been raised on the LM forum where one user has reported:

>  can confirm the issue on a Thinkpad X220, running VirtualBox 5.2.22 and 6.0.0 as a Linux host (LM 19 Cinnamon after upgrade to 19.1) with Linux and Windows 7 clients. Haven't tried other flavours of Mint. Some Ubuntu 18.04 flavours I tried are not affected.

and another:

> For reference, seamless mode is working flawlessly on my LM19.1 MATE.

Further information with screenshots:

https://forums.linuxmint.com/viewtopic.php?f=47&t=284141&p=1574464#p1574464

**Comment by antoniodourado** [comment]
Any update on this issue? I'm using Mint 19.1, VB 6.0.10 and Win10 as guest, but seamless mode isn't working so far.
My muffin version is 4.0.7.
Thank you.
