### ISSUE TITLE
Disable compositing on full-screen setting unreliable

### ISSUE THREAD

**Issue by Mister-Dolus** [linuxmint/muffin#409]
muffin 4.0.5
Linux Mint 19.1
RX 480 with Mesa
64-bit

**Issue**
Disable compositing on full-screen setting doesn't always work on start up

**Steps to reproduce**
Toggle 'Disable compositing for full-screen windows' and run a game with vsync turned off.

**Expected behaviour**
Games should bypass the compositor

**Other information**
Games which have vsync shut off should have some tearing, but the compositor isn't being bypassed unless you restart Cinnamon. The problem is that you have to restart Cinnamon again after re-toggling the setting on start up. It also seems that after some time, fullscreen windows still fail to bypass the compositor anyway.

**Comment by jaszhix** [comment]
Which games are you trying to disable compositing for? There's a known issue with Wine games not being unredirected (#400).

**Comment by Mister-Dolus** [comment]
I've been playing around with it, and it seems that even after a restart, Cinnamon will start ignoring the setting again during the same session. Even with native games like Rise of The Tomb Raider. I have not been able to pin down the timing. Might be random.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/muffin/commit/c32027f822d83c6e3033815c182384a82b6857dd
