### ISSUE TITLE
[Dual monitor] Window menu opens on wrong monitor

### ISSUE THREAD

**Issue by autarkper** [linuxmint/muffin#41]
Steps to reproduce (current master):

1. Set up a dual-monitor configuration.
2. Move a window from the primary to the secondary monitor.
3. Open the window's window menu with the ALT+space hotkey.
4. Activate a window that's on the primary monitor.
5. Open that window's window menu using the same hotkey.

Desired behavior: in all cases, the window menu should open at its expected position inside the window.
Actual behavior: the second window menu is opened outside its window, on the wrong monitor.

**Comment by JosephMcc** [comment]
This seems to work as expected now.
