### ISSUE TITLE
Scroll bars lose focus while window is being dragged

### ISSUE THREAD

**Issue by rsi9x** [linuxmint/muffin#414]
```
 * muffin version 4.0.6

System:    Kernel: 4.18.0-13-generic x86_64 bits: 64 Desktop: Cinnamon 4.0.9 Distro: Linux Mint 19.1 Tessa 
Graphics:  Device-1: NVIDIA GP106 [GeForce GTX 1060 3GB] driver: nvidia v: 415.27 
           Display: x11 server: X.Org 1.19.6 driver: nvidia unloaded: fbdev,modesetting,nouveau,vesa 
           resolution: 1600x1200~60Hz, 1920x1200~60Hz, 1600x1200~60Hz 
           OpenGL: renderer: GeForce GTX 1060 3GB/PCIe/SSE2 v: 4.6.0 NVIDIA 415.27 

 ```

**Issue**

When moving the Firefox window, the scroll bars seem to behave as if the window had lost focus.  They go into low contrast mode when the window being dragged, then go back into high contrast (in focus) mode  when the window is placed its new position.  Forms and other elements within the web page also behave as if they had momentarily lost focus while dragging the window.

**Steps to reproduce**

Open a web page in Firefox large enough to produce scroll bars, then move the window around the screen.  Scroll bars will change to low contrast mode while the window is being moved, as if the window had lost focus.

**Expected behaviour**

Scroll bars should remain in high contrast mode while the window is being dragged, as it is in focus.

**Other information**

Admittedly, this is kind of a minor issue, but it makes the user experience a little clunky.  Not sure if this belongs in Muffin or Cinnamon - please move if necessary. Thanks in advance!

**Comment by jaszhix** [comment]
Not reproducing this. Which theme are you using?

**Comment by rsi9x** [comment]
Window Borders: Mint-Y-Dark
Icons: Mint-Y-Blue
Controls: Mint-Y-Darker-Blue
Mouse Pointer: DMZ-White
Desktop: Mint-Y-Dark-Blue

**Comment by JosephMcc** [comment]
This issue is old and I can't reproduce it. Plus we've had a lot of new versions of Firefox since then.
