### ISSUE TITLE
[Feature request, Dual-monitor] Window menu should include options to move window to another monitor

### ISSUE THREAD

**Issue by autarkper** [linuxmint/muffin#42]
If more than one monitor is detected, the window menu should include options to move the window to another monitor, similar to the workspace-movement menu options added when multiple workspaces are in use.

**Comment by kohloth** [comment]
I would like to have this feature too. Pressing Super+Left moves the current window to occupy the left half of the screen. If you press it again, maybe it could move the window to fill the right half of the next screen over, as with Windows 7.

**Comment by still-dreaming-1** [comment]
@clefebvre what is the window list?

**Comment by ahmadnassri** [comment]
@still-dreaming-1: window list == window panel

**Comment by z3cka** [comment]
Pressing Super+Shift+Left/Right does the trick for me.

**Comment by migueloop** [comment]
For me, it works great, thanks a lot! (Cinnamon 2.6.12)

**Comment by jreuter** [comment]
The version of Mint I have is running 2.4.8 so I don't have the keyboard shortcut.  I found this that solved it for me: https://github.com/ntowbinj/switch-monitor

**Comment by YuraKostin** [comment]
Thanks too much, @z3cka =)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by Condobloke** [comment]
Has there been any movement with this requested feature?
