### ISSUE TITLE
[Dual Monitor] Alt+F7 Window movement artificiallly restricted.

### ISSUE THREAD

**Issue by autarkper** [linuxmint/muffin#45]
I have a dual-monitor setup with a lower-resolution (1200x800) monitor positioned left of a high-resolution (1920x1200) monitor, bottom-aligned with each other. In this setup I cannot move a window to the lower part of the left-hand monitor using the Alt+F7 hotkey; the motion stops round the middle of the screen, probably when the bottom of the window reaches 800 pixels from the top of the virtual screen.

**Comment by guicara** [comment]
Hello,

I don't know if it is the same problem, but I have some issues with my dual-monitor configuration in Linux Mint Cinnnamon 17.2 (with Muffin). My primary display is my laptop screen (1920x1080) and my secondary display is a 29" Dell (2560x1080). I will illustrate the problem with the following screenshot:

![Screenshot 1](http://s18.postimg.org/68zicuj1h/Min_multiscreen_windows_bug_1.jpg)
Full screen: http://s18.postimg.org/a5cu8u415/Min_multiscreen_windows_bug_1.jpg

![Screenshot 2](http://s23.postimg.org/wq5ou2adj/Min_multiscreen_windows_bug_2.jpg)
Full screen: http://s23.postimg.org/xfoh6fax7/Min_multiscreen_windows_bug_2.jpg

Thanks,

**Comment by icarter09** [comment]
@autarkper are you still experiencing this issue?
