### ISSUE TITLE
Brightness flickering with freesync enabled

### ISSUE THREAD

**Issue by dron1885** [linuxmint/muffin#462]
```
 * muffin version 4.0.7-1
 * Cinnamon - 4.0.1
 * Distribution - Antergos (Arch variant)
 * AMD RX 580, Mesa 19.1.0_devel (and 19.0.0)
 * 64 bit
 ```

**Issue**
When running with freesync enabled there is a brightness flickering. (And judging by a mouse movement stutter a refresh rate is lower than nominal, especially noticeable with a higher refresh rate).

When some 3d app is running (ex. glxgears) everything is fine.

**Steps to reproduce**
Start Cinnamon desktop with freesync enabled.

**Expected behavior**
No flickering and mouse stuttering.

**Other information**
With xfce freesync works without problems.
(Not sure if muffin or Cinnamon bug, seems more like a former one.)
Off-topic: Ability to set monitor refresh rate in System Settings>Display would be very convenient.

**UPDATE**: after further testing I've found out that some other DE are affected as well, so it's probably a Mesa bug.

**Comment by leogx9r** [comment]
I can also confirm this is an issue. Took some time to narrow it down to Muffin/Cinnamon.

```
 * Muffin - v4.4.2
 * Cinnamon - v4.4.8
 * Distribution - Arch Linux
 * CPU - Ryzen 7 3700X
 * GPU - AMD RX 5700XT
 * Mesa 20.1.0_devel (#500842399a3)
```

**Comment by dron1885** [comment]
@leogx9r 
It's bug within mesa blacklisting. They blacklist `muffin`, but for Arch correct process is `cinnamon`. 
Look into `/usr/share/drirc.d/00-mesa-defaults.conf`.

I tried to push "patch" through gitlab, but encountered mouthful of errors (yeah I lazy af). 

For my system I've fixed it by creating a pacman hook:

```
[Trigger]
Operation = Install
Operation = Upgrade
Type = Package
Target = mesa
Target = mesa-*

[Action]
Description = Adding Cinnamon DE to freesync blacklist
When = PostTransaction
Exec = /usr/bin/sed -i -e 's/muffin/cinnamon/g' /usr/share/drirc.d/00-mesa-defaults.conf
```

**Comment by leogx9r** [comment]
@dron1885 Holy hell, thanks a lot mate. That fixed it. 

Genuinely never thought of looking at mesa's blacklist for this issue.

**Comment by leigh123linux** [comment]
Upstream PR submitted

https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4316

**Comment by karelfridrich** [comment]
@dron1885 When I do this, the flickering stops, freesync is disabled as expected. But then it never works in any game I tried (DOTA2, CSGO, DOOM). Maybe because Cinnamon is still running in background?

**Comment by SakiiCode** [comment]
> But then it never works in any game I tried (DOTA2, CSGO, DOOM).

@karelfridrich Got this working by disabling my secondary monitor before launching the game. You can automate it with gamemode

_/etc/gamemode.ini_

```
[custom]
start=xrandr --output <port> --off
end=xrandr --output <port> --right-of/--left-of <main monitor port> --rate <secondary refresh rate> --mode <secondary resolution>
```

This actually makes freesync fully usable with a dual monitor setup on Linux Mint, I'm so happy now after days of investigation

Sorry for the necro, but that merge should really happen for mesa.
