### ISSUE TITLE
Fullscreen applications are not drawn correctly

### ISSUE THREAD

**Issue by TrickMe** [linuxmint/muffin#530]
Muffin 4.2.2+tina
Mint 19.2
AMD RX 570, mesa 19.1.2-0bpadoka0
64 bit

**Issue**
In fullscreen applications, the lower and right-hand rim are not drawn and show the desktop background.

**Steps to reproduce**
Start a full-screen application

**Expected behaviour**
Application drawn and updated on whole screen area.

**Other information**
I opened a similar issue on cinnamon-git and will close that one now.

**Comment by Leopard1907** [comment]
Same issue exists on my end as well. As usual , devs are dead silent.

**Comment by Leopard1907** [comment]
Screenshot that shows the issue:

![Ekran Görüntüsü - 2019-09-01 01-00-12](https://user-images.githubusercontent.com/24878978/64069662-9d4f8980-cc56-11e9-8455-1d515bec21ba.png)

**Comment by Leopard1907** [comment]
A known workaround for this is disabling window effects on Cinnamon.

Throwing rocks into a deepless well at this point but...

**Comment by smurphos** [comment]
> A known workaround for this is disabling window effects on Cinnamon.
> 
> Throwing rocks into a deepless well at this point but...

Switching Effect's style from the default Cinnamon may also have mileage. For example I can't seem reproduce the issue with the Scale effects style set.

**Comment by smurphos** [comment]
By the way pretty sure this is GPU independent. I'm seeing was seeing it intermittently on Intel Integrated graphics with the default Effects set.

**Comment by smurphos** [comment]
Hi,

So an update from a little bit of testing - another user on the Mint forum reports the same.

The issue manifests with the Effects style set to Cinnamon, Fade or Blend. It can't be reproduced with any other effects style.

Using the Customise option and effectively recreating the Scale effects in the Cinnamon effects style also cures the issue, but I've not been able to narrow the problem down to one particular Effects sub-setting in the Customise GUI. 

I can't really spot what the 3 problematic Effects styles have in common either.

**Comment by TrickMe** [comment]
@smurphos @Leopard1907 thanks for your participation. I hope it will help getting to the bottom of the issue.

**Comment by smurphos** [comment]
OK - narrowed down the issue to the Mapping Windows sub effect. Having this set to Traditional, Fade or Blend manifests the issue. Anything else is fine.

![screenshot-window-2019-10-06-053550](https://user-images.githubusercontent.com/29017677/66264338-54619680-e7fb-11e9-8aea-855df8c8bf37.png)

**Comment by TrickMe** [comment]
@smurphos Which theme are you using if I may ask? Looks very nice.

**Comment by smurphos** [comment]
Cinnamox-Rhino - it's on Cinnamon Spices so you can install it via the Themes settings module.

**Comment by mrdeepmind** [comment]
I had the same issue but as @smurphos said before, changing effect style Cinnamon to "Scale" fixed my problem for now. I'm on Fedora 30.

**Comment by ImpWarfare** [comment]
I'm having a similar issue with Cinnamon on Arch Linux with full screen games and on a game called The Station which is a steam game. The game goes full screen but it reveals something in the bottom right corner of the screen which is annoying I believe sometimes it shows the wallpaper on the desktop and parts of the taskbar as well. I hadn't had this before with Cinnamon on Arch only on the recent versions.

**Comment by ImpWarfare** [comment]
Also it sometimes shows like a blue glowing line along the edge of the bottom right on the corner.

**Comment by ImpWarfare** [comment]
Is it possible someone who knows how to use Arch Linux tries The Station video game with Cinnamon and see if they get the same bug as I do.

**Comment by ImpWarfare** [comment]
The Theme which I tend to use is the Tyr Himinn theme this: https://cinnamon-spices.linuxmint.com/themes/view/Tyr-himinn and with this wallpaper https://i.pinimg.com/originals/df/8b/f2/df8bf29ea58ab86f4b92cb04983e0d02.jpg

**Comment by ImpWarfare** [comment]
I too am having this issue with steam but for Arch Linux on a game called The Station with the nvidia drivers installed its showing a line on the bottom right and bottom bottom of the right side of the screen. This I don't remember happened on the 3.x or earlier but only recently with v4.x.

**Comment by cyan-lime** [comment]
I've had the same issue on Fedora 30 with Cinnamon. NVIDIA graphics here, agree that the issue is GPU independent. I also agree it's certain window animations causing the issue.

Changing the 'mapping' animation ensures the problem doesn't occur when opening a new fullscreen window. However, the issue will still occur when restoring the window by clicking its window button on the panel. To stop this, you need to change or turn off the 'minimizing' animation as well. For me, changing both the 'mapping' and 'minimizing' animations from 'traditional' to 'scale' seems to have eliminated the issue. 

Here's another image of the problem in action. It occurs nearly universally across native Linux games, but I haven't been able to reproduce it in programs launched through WINE.

![image](https://user-images.githubusercontent.com/54386705/67628327-6e9d0a80-f8b7-11e9-8e33-00ec3317fa7a.png)

**Comment by Leopard1907** [comment]
Wine as any custom wine build with fshack or Proton?

Fshack is simply fullscreen hack ( a temporary solution ) so it might explain why it is not happening on those.

**Comment by JustinSpedding** [comment]
I am also experiencing the same issue. It happens with both native and proton/wine games. Disabling the cinnamon window effects fixes it, but is not ideal because the window effects are nice.

Mint 19.2
GTX 1080 w/ proprietary nvidia drivers v440.26 (Also happened with the 435 and 430 driver lines)

**Comment by mtwebster** [comment]
Hi, can you guys give me a bit more info please - I can reproduce this most of the time, but only along the bottom edge of the screen, and only on a steam game so far. 

- Number of monitors
- Which monitor do you use as primary (if more than 1)
- List the program(s) this occurs on.  Specify if they're native packages (deb, rpm, etc..) or flatpak, steam, wine, etc..

Thanks

**Comment by Leopard1907** [comment]
My setup:

- One monitor ( laptop )
- Compositor disabled
- Usually with games. As in ; a normal Steam installation ( official .deb package ) and a native Linux game being set to run in fullscreen via game settings is more than enough to repro. I noticed it on Rocket League for example.
-I didn't test if it exists on titles running through Proton. Might not be , maybe fshack does prevent such stuff. 
- Disabling window effects solves the issue completely. Another user above gone further and identified which ones are problematic while other ones doesn"t break fullscreen apps.

**Comment by JustinSpedding** [comment]
If I remember correctly, I could consistently reproduce this every time with the Mortal Kombat games running through Proton on Steam (specifically MK 9 Komplete Edition). However, I have not played these in a while. When I was playing it back then, I had 1 monitor at 1440p 144Hz (although the game was capped at 60). I had compositioning disabled for full-screen windows in the cinnamon settings, had vsync disabled in favor of nvidia composition pipeline, and was using the cinnamon-style desktop effects.

**Comment by smurphos** [comment]
Hi Michael,

Single Monitor, Laptop - I see it reasonably consistently running a Virtualbox guest in full screen mode with  the relevant effects set - a few pixels of the host wallpaper is visible on the bottom and right edges.  Vbox 6.0.14 - guest is also Mint with 3D acceleration enabled using the VMSVGA driver.

**Comment by mtwebster** [comment]
Hi, can I get any of you to try these packages?

https://www.dropbox.com/sh/k8ixh4f0qw9iqou/AABvtdqjmbXwxVrNMApPTVW_a?dl=0

Just download, open a terminal in that folder, and run:
```
sudo dpkg -i *.deb
```
then restart cinnamon (or log out/in).

This is a potential fix for something else, but I have a feeling it may fix this as well.  I can't reproduce the issue on my machine anymore with it, though I could never do it reliably, regardless.

You can switch back to distro-versions vy allowing mintupdate to upgrade them.

Thanks

**Comment by smurphos** [comment]
Hi Michael - tested with those packages on Cinnamon 4.4.3 and 4.2.4 with Effects set to Cinnamon and they don't solve the issue. To reproduce I invoke the issue by running a Virtualbox (6.0.14) guest using VMSVGA in full screen mode. If I use the Vbox tool bar to minimise the window and then restore the full screen window will show the host desktop wallpaper on the right and bottom edges of the screen

**Comment by mtwebster** [comment]
Please check the above post again: https://github.com/linuxmint/muffin/issues/530#issuecomment-563476189

I've put up new packages (and a set for users still on cinnamon 4.2)

Thanks

**Comment by smurphos** [comment]
@mtwebster - Hi, the updated packages seem to have resolved the issue on both 4.2 and 4.4 with the virtualbox test case

**Comment by Leopard1907** [comment]
Cinnamon 4.4.5 shipped with Mint 19.3 ( upgraded from 19.2 ) still have this issue.

**Comment by mtwebster** [comment]
It was fixed after the iso was finalized, it will be in a muffin update soon.  In the meantime, you can safely install the packages (following the instructions) I linked above for 4.4, that include the fix.

Just remember to de-select cinnamon-muffin from mintupdate for the time being, as it will always want to install the 'official' version.

**Comment by Leopard1907** [comment]
Thanks for the answer.

**Comment by akaIDIOT** [comment]
Hmm, was hitting this same issue on my laptop running Mint 19.3, installed the packages from the dropbox link and they seem to not be totally fixed. 

Notice the single line of pixels on a maximized firefox window:

![Screenshot from 2020-02-02 15-08-29](https://user-images.githubusercontent.com/144798/73609483-7105b380-45ce-11ea-9699-5796697a76bb.png)

Effects settings as such:

![Screenshot from 2020-02-02 15-13-15](https://user-images.githubusercontent.com/144798/73609509-a6aa9c80-45ce-11ea-9916-0cb88ad9803e.png)

~~~~ plain
$ dpkg -l | grep muffin
hi  gir1.2-meta-muffin-0.0                     4.4.1                                           amd64
hi  libmuffin0                                 4.4.1                                           amd64
hi  muffin                                     4.4.1                                           amd64
hi  muffin-common                              4.4.1                                           all
hi  muffin-dbg                                 4.4.1                                           amd64
~~~~

I'm assuming this is essentially the same thing / bug, can I add anything else to clarify or test things?

**Comment by JpegXguy** [comment]
I have this as well. Firefox maximized has pixel border on the right. Chrome and firefox fullscreen video has border on the right and the bottom

**Comment by JpegXguy** [comment]
Disabling window effects and restarting with Alt-F2 and typing 'r' fixed it temporarily.
Then after reenabling the window affects and restarting, it stays fixed. Maybe it'll reappear on reboot

**Comment by mtwebster** [comment]
What happens if you maximize the window using either a shortcut (ctrl-shift-m by default) or via tiling shortcuts (super-up-arrow twice)?

I'm pretty sure these recent reports are caused by this firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1604921

I can reproduce that particular bug here - it's supposed to be fixed in firefox 73.  You can also workaround it by turning on the title bar (bottom left corner of the firefox 'customize' view).

The shortcut test would confirm this is the firefox bug.

**Comment by akaIDIOT** [comment]
- I'm seeing this after maximizing firefox using the shortcuts (the only way I ever do, really);
- when enabling the firefox title bar, not touching the size of the window otherwise, can't see the single pixel line of my desktop bg;
- disabling the title bar again (which unmaximizes the firefox window) and maximizing it again using the hotkey, the window actually fills the screen again;
- closing firefox, opening it back up again, problem seems gone, ... **until** the master password dialog pops up, suddenly eating a few pixels off the right, after which maximizing the firefox window after pressing escape on the dialog, the rightmost line of pixels is my desktop bg again.

Noticed the last bit just now, can't comment on whether every occurrence of the problem was ever after a (modal) dialog, but the window seems a bit mangled in floating mode now too (see screenshot, closing cross usually aligns):

![Screenshot from 2020-02-04 21-01-17](https://user-images.githubusercontent.com/144798/73782053-aad2e780-4791-11ea-8f77-62942ddf0216.png)

After this, toggling firefox' title bar on and back off again (I like it off), the window is back to normal again (both maximized and floaty). Could check and test a lot more things if need be, seems somehow deterministic yet hard to really put a finger to :thinking:

**Comment by mtwebster** [comment]
Could you try out the firefox developer edition?
https://www.mozilla.org/en-US/firefox/developer/

Basically unzip it and run ./firefox from that folder

I tried it and I don't see the issue anymore, but extra data would be good.

**Comment by akaIDIOT** [comment]
Live from the dev edition, problem persists, cap'n. But again, only after I pointed the thing to a backup of my profile and triggering the master password popup. Fun thing: the modal extraction dialog of the archive manager did the same thing, albeit a tad more extreme:

![Screenshot from 2020-02-04 21-19-17](https://user-images.githubusercontent.com/144798/73783948-df946e00-4794-11ea-8d4f-ddc56d964f74.png)

Right side of the screen shows a bunch of timestamps in the nemo window behind the archive manager, which remained chewed after the dialog was closed... Seems this might not be firefox-related after all? Or firefox might be messing with things outside its own window / process?

**Comment by mtwebster** [comment]
Are you still on muffin 4.4.1?  Can you upgrade to 4.4.2?

**Comment by akaIDIOT** [comment]
Unheld the gir / muffin packages listen on dropbox before, now all on `4.4.2+tricia`, problem now easily reproducable with the archive manager, seeing the same kind of chunk missing from the right after an extract. The same thing holds for thunderbird and firefox after a password prompt.

**Comment by breversa** [comment]
Still happening on my system, sadly :
```
System:    Host: [REDACTED] Kernel: 5.8.0-33-lowlatency x86_64 bits: 64 Desktop: Cinnamon 4.6.7 Distro: Linux Mint 20 Ulyana

Graphics:  Device-1: NVIDIA GM200 [GeForce GTX 980 Ti] driver: nvidia v: 455.45.01 
           Display: x11 server: X.Org 1.20.8 driver: nvidia unloaded: fbdev,modesetting,nouveau,vesa 
           resolution: 1920x1200~60Hz 
           OpenGL: renderer: GeForce GTX 980 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 455.45.01
```

**Comment by mikeshiyan** [comment]
Only now I found this thread, after few years living with that stupid border. How can you call it fixed if it requires manual steps like changing settings or installing packages?

**Comment by The-Shotgun** [comment]
Still happening on Linux Mint 20.3

**Comment by The-Shotgun** [comment]
Seems like going windowed then fullscreen again is a temporary fix, but it goes away on the next application launch

**Comment by ijash** [comment]
on extended monitor. i still see the border on linux mint 21.3 cinnamon
