### ISSUE TITLE
Prevent focus stealing stops session dialogs launched by keyboard shortcut getting focus

### ISSUE THREAD

**Issue by smurphos** [linuxmint/muffin#536]
```
 * muffin version 4.22
 * Distribution - Mint 19.2
 * Graphics hardware *and* driver used
Graphics:  Device-1: Intel vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:3ea0 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics (Whiskey Lake 3x8 GT2) v: 4.5 Mesa 19.0.8 compat-v: 3.0 
           direct render: Ye
 * 64 bit
 ```

**Issue**
Not sure if this is a bug or is working as intended but if Prevent Focus Stealing is checked session dialogs launched by keyboard shortcuts (Ctrl-Alt-Delete or Ctrl-Alt-End) fail to get focus. I don't see this as focus stealing when the end-user has specifically invoked the dialog.

**Steps to reproduce**
With prevent focus stealing checked launch a session dialog via keyboard shortcut. Get mildly annoyed as you can't then tab through the options without either reaching for the mouse or Alt-tabbing to bring the dialog into focus.

**Expected behaviour**
Prevent Focus Stealing should have no effect on session dialogs launched by keyboard shortcut.

**Other information**

**Comment by anatoly-tiukov** [comment]
Not actual anymore. 'Ctrl+Alt+Del' works correct.
