### ISSUE TITLE
Ubuntu's work on Mutter and Possible learning for Muffin.

### ISSUE THREAD

**Issue by HennieLouw** [linuxmint/muffin#539]
Hi Linux Mint Team.
I'm a long time user of Mint and came across an interesting article on Ubnutu's discourse.
https://discourse.ubuntu.com/t/boosting-the-real-time-performance-of-gnome-shell-3-34-in-ubuntu-19-10/13095

From the little I understand, most of the work has been done on Mutter which Muffin is based on and not the Gnome Shell itself.

I'm not aware of the integration and/or relationship of when Muffin branched off from Mutter, but I'm hoping that tagging this article might is some way help drive the creative spark which makes software better by seeing what others have done.

Feel free to close this if it's not the right place or relevant to the project.

**Comment by JosephMcc** [comment]
Not closing this because it isn't helpful but we already keep an eye on upstream mutter. Thanks.
