### ISSUE TITLE
[Feature] Wayland Support Devel Metatask

### ISSUE THREAD

**Issue by ItzSwirlz** [linuxmint/muffin#573]
Add wayland support for muffin.

GDM: See https://github.com/GNOME/gdm/blob/master/daemon/gdm-wayland-session.c (browse more through the official GitLab)

cinnamon-session needs the most work. See linuxmint/cinnamon-session#137

**Comment by mtwebster** [comment]
No, that's not right..

That file you're linking is probably part of gdm's (gnome's login manager) wayland implementation - I imagine so they wouldn't continue to need x11 for gdm before switching to wayland for the user session.

For cinnamon, far and away the largest amount of work would be with muffin. To the degree that it's probably throw-away at that point. There would be a lot of work in many other packages also.

This has no urgency at all for us right now, so I really don't think we need meta-issues for anything (in fact you can probably find other older issues). It's something we'll have to deal with eventually but that's it for the moment.

**Comment by LinuxOnTheDesktop** [comment]
Is supporting Wayland considered urgent yet? Perhaps it should be, given that Wayland: provides good fractional scaling; provides various other benefits; and looks set, soon-ish, finally to become the standard for Linux.
