### ISSUE TITLE
Muffin crash with COGL when cinnamon closes muffin on replace

### ISSUE THREAD

**Issue by ItzSwirlz** [linuxmint/muffin#580]
```
 * muffin version 4.8.1
 * Distribution - Ubuntu Cinnamon Remix 21.04 Hirsute Hippo (in development branch currently)
 * Intel Core i5 7th Gen, built-in GPU. Dell Inspiron 15-3567
 * 64 bit
 ```

**Issue**
Muffin and Cinnamon don't have good relationships when replacing each other. Unlike cinnamon where running --replace will quietly quit the existing muffin, cinnamon ends up actually *segfaulting* muffin. It's why in fish, when you try running:
```
muffin --replace
cinnamon --replace
```

in two tabs and go back, you will see muffin segfaulted.

Here is the crash:
```
Mar 23 14:36:09 Joshua-UCRTest kernel: [ 1113.176029] muffin[7196]: segfault at 0 ip 0000000000000000 sp 00007ffc2fe23418 error 14 in muffin[561283431000+1000]
```
addr2line traces it to 
```
cogl_quaternion_init_from_euler
./cogl/cogl/cogl-quaternion.c:237
```
**Steps to reproduce**
Open a terminal, you will need two tabs.
In the first, start muffin. (```muffin --replace```)
In the second, start cinnamon with replacement, to close muffin (```cinnamon --replace```)

BTW: If you do the opposite, running cinnamon --replace first and then muffin --replace, cinnamon closes fine. The way it quits muffin is just incorrect.

**Expected behaviour**
No segfault (although honestly who would do this? I'm a crazy guy)

**Comment by leigh123linux** [comment]
A: We expect a full backtrace.
B: Your 'muffin --replace' usage is bogus as we only use muffin libs.
C: If you can reproduce a valid crash feel free to reopen the issue.

**Comment by ItzSwirlz** [comment]
> A: We expect a full backtrace.
Mostly full of crap because I also tried reproducing a nemo crash but I'll attach it, I intentionally decided not to give it and limit it down.

> B: Your 'muffin --replace' usage is bogus as we only use muffin libs.
Then what's the point of the executable being made then? Cinnamon can technically on it's own handle muffin startup.

> C: If you can reproduce a valid crash feel free to reopen the issue.
Okay, then you can feel free to either remove the --replace option and/or the executable and only keep it in cinnamon... And also while you're at it close # 554, that also uses muffin --replace.

[.xsessionerrors.txt](https://github.com/linuxmint/muffin/files/6192118/def
[syslog.txt](https://github.com/linuxmint/muffin/files/6192123/syslog.txt)
ault.xsessionerrors.txt)

**Comment by leigh123linux** [comment]
> > B: Your 'muffin --replace' usage is bogus as we only use muffin libs.
> 
> Then what's the point of the executable being made then? Cinnamon can technically on it's own handle muffin startup.
> 
> Okay, then you can feel free to either remove the --replace option and/or the executable and only keep it in cinnamon... 

I think muffin binary is mainly used for development debugging by @mtwebster 
I removed the muffin binary in fedora for several releases because I was spammed with bug reports from XFCE users trying to use as a WM.
