### ISSUE TITLE
Cinnamon menu and taskbar hide Japanese Input prediction.

### ISSUE THREAD

**Issue by luyikei** [linuxmint/muffin#59]
Not just iBus but also SCIM.
![ibus.png](https://f.cloud.github.com/assets/1858413/2276/4fd89a68-41dc-11e2-818f-6f6eeb401b4c.png)

**Comment by leigh123linux** [comment]
If this commit doesn't fix the issue feel free to reopen.

https://github.com/linuxmint/muffin/commit/5d6ec8b9fad2e21c05a820484e34998f515fa711
