### ISSUE TITLE
Muffin window tile push bug when using the keyboard shortcuts (cropped and doubled edges)

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/muffin#591]
```
 * muffin version: 5.0.1
 * Distribution: Linux Mint Cinnamon 20.2
 * Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 2000 (SNB GT1) v: 3.3 Mesa 20.2.6 
 * 64 bit
 ```

![Cinnamon-20-2-Muffin-bug-1](https://user-images.githubusercontent.com/31940713/125164802-13ca4600-e162-11eb-9609-ae8be42a3cd0.png)
_(Click to enlarge)_

**Issue**
Muffin window tile push bug when using the keyboard shortcuts. I push tile left, then change my mind and try to push tile right, but it doesn't work, i try again, and i end up with a cropped edge and a doubled edge: see screenshot.

**Steps to reproduce**
1. Use any common app such as Xed, or Nemo, or Firefox, etc.
1. Press Super+Left to push tile left: result = okay
1. Press Super+Right to push tile right: result = nothing changed
1. Press Super+Right to push tile right again: result = distorted (cropped on the right side, leaving empty space, and double edges on the left side, as showed in the screenshot)

**Expected behaviour**
I would expect the window size to be half-width (in this case 1920/2=960px) and positioned on the right side of the screen and displayed without any distortion or cropping.

**Other information**
* Also re-tested on a fresh 20.2 install on VirtualBox without any custom settings (or almost...)
* I never had this problem on Mint 20.1 and previous versions.

**Comment by mtwebster** [comment]
caused by 45c631cfc34de502
