### ISSUE TITLE
When will the next version of muffin be released? (Concerning Issue 591)

### ISSUE THREAD

**Issue by 392781** [linuxmint/muffin#597]
```
 * muffin version 5.0.1
 * Distribution Mint 20.2
 ```

I've been stuck with issue #591 for over a month now... I understand that this was fixed but I am wondering when will the next official release be?  I'm not sure if there is a PPA or not for the unstable Muffin release which has the fix to that issue (I couldn't find one)... 

Or is the only option for now to downgrade to previous package release on Mint?

**Comment by clefebvre** [comment]
There will be a point release this month.
