### ISSUE TITLE
clutter/Makefile.am:652: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL

### ISSUE THREAD

**Issue by neofeo** [linuxmint/muffin#610]
trying to compile main on ubuntu focal aarch64
failed on autogen..

clutter/Makefile.am:652: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL

**Comment by leigh123linux** [comment]
Try installing the build requires.

https://github.com/linuxmint/muffin/blob/master/debian/control#L10

Similar PICNIC issues.

https://github.com/linuxmint/muffin/issues/67

https://github.com/solus-project/budgie-desktop/issues/31

**Comment by neofeo** [comment]
Okay, thanks!
