### ISSUE TITLE
Hellpoint (v366) has very bad frame rates

### ISSUE THREAD

**Issue by Machion** [linuxmint/muffin#613]
```
 * muffin version - 5.2.1
 * Distribution - Manjaro Cinnamon
 * Graphics hardware *and* driver used - AMD Radeon HD7790 with amdgpu
 * 32 or 64 bit - 64bit
 ```

**Issue**
Hi, I don't know, if this problem is related to muffin, but would be happy to research together: 

So I tried playing Hellpoint (GOG Linux version 366, Unity-Engine) on my Manjaro PC and it was unplayable because framerates dropped below 10fps!

I tested it on Win7 (same PC) and on a Manjaro notebook with no problems. Details below:

1. PC - AMD Ryzen 5 2600, 8GB RAM, AMD Bonaire XT/Radeon HD 7790

    Manjaro Linux (Cinnamon), Kernel 5.15, amdgpu 22.0.0, Mesa/Vulkan 21.3.7-2 > bad framerates (vkcube runs good)
    Win7, 64bit > good framerates

2. PC (Notebook) - AMD Ryzen 3 5300u, AMD Renoir Graphics, 8GB RAM

    Manjaro Linux (Gnome), Kernel 5.15, amdgpu 22.0.0, Mesa/Vulkan 21.3.7-2 > good framerates

The test with Win7 just shows, that the old graphics card in my first PC is not the problem. Which leads me to the question: What is the difference between those two Manjaro Editions?

Obviously the DE or in detail Gnome runs on wayland. But is this really the point?
Any suggestions? Thanks in advance.

**Comment by leigh123linux** [comment]
Try installing cinnamon on PC#2 and see if the issue reproduces.

**Comment by leigh123linux** [comment]
Feel free to reopen if you can reproduce.

**Comment by Machion** [comment]
So I installed Manjaro Cinnamon on PC#2 and surprisingly it worked. 
This means the problem lies in the combination of the graphic card in PC#1 and amdgpu right?

**Comment by leigh123linux** [comment]
Try filing the issue against mesa or amdgpu driver.
