### ISSUE TITLE
LM Cinnamon 21 minimize-maximize-close buttons are not the same for all windows when choosing the icon theme

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/muffin#629]
```
 * muffin version: mutter 5.4.5
 * Distribution: LinuxMint Cinnamon 21 — all up-to-date
```
on VirtualBox: [VM-inxi-2022-08-04.txt](https://github.com/linuxmint/muffin/files/9264028/VM-inxi-2022-08-04.txt)
`inxi -Fxxxrz > /media/sf_VirtualBox_Shared/VM-inxi-$(date +%Y-%m-%d).txt`

**Issue**
In LinuxMint 21, in `cinnamon-settings themes`, when choosing Mint-Y-Aqua for applications and Mint-X-Aqua for icons, the minimize-maximize-close buttons are not the same for all windows

**Steps to reproduce**
1. Open `cinnamon-settings themes` and the calculator, side-by-side, to compare (that's just one example amongst others...)
2. Choose Mint-Y-Aqua for applications and Mint-X-Aqua for icons
3. See? Those two windows do not share the same style for the 3 window buttons (minimize-maximize-close buttons)

**Expected behaviour**
I would expect to be able to select my preferred icons theme without altering the window borders. Also, I would expect all windows to always share the same style.

**Screenshots**
![LM21-Icons-Apps](https://user-images.githubusercontent.com/31940713/182971796-d0b4fd62-16c3-4e55-879d-6de4109c6222.png)

**Other information**
I am totally puzzled and I am not even sure I am in the right repository for this issue.

**Comment by SebastJava** [comment]
@JosephMcc is this a `mint-themes` issue? or `muffin` issue? or `cinnamon-settings themes` issue? or other issue?

Or else, if the window buttons are now part of the icons theme, I would at least expect the icon theme to be the same across all windows, for the window buttons. But I would be very surprised the window buttons are now defined by the icons themes.

**Comment by leigh123linux** [comment]
Try blaming GTK4 and libhandy instead.

**Comment by mfreeman72** [comment]
> Try blaming GTK4 and libhandy instead.

I don't think anyone's "blaming" anything. Just trying to figure out why it's happening and how it might be fixed. Interesting thing is, if the problem is with GTK4 and libhandy, then why should the Mint themes be the only ones that exhibit this problem out of all the themes I've downloaded and installed to try? I'm sure that if all those other themes can show the correct window controls across all window types, then there must surely be a way to get Mint's themes to manage it as well.

**Comment by SebastJava** [comment]
This seems to be a mint-themes issue. And there is an opened issue there about this: https://github.com/linuxmint/mint-themes/issues/397
