### ISSUE TITLE
attach modal dialog inactive in dconf

### ISSUE THREAD

**Issue by geoffmen** [linuxmint/muffin#64]
dconf's org/cinnamon/muffin/attach-modal-dialogs is not effective. I would expect it to correspond to "Cinnamon Settings" - Windows / Attach dialog windows to their parent window's titlebar. I don't know where in dconf this setting is. (must rely on cinnamon settings interface)

**Comment by JosephMcc** [comment]
org.cinnamon.muffin attach-modal-dialogs is the proper key. It works fine here using dconf.
