### ISSUE TITLE
Muffin v5.4.7 missing window menu shortcut key

### ISSUE THREAD

**Issue by nzlosh** [linuxmint/muffin#644]
```
 * muffin version (muffin --version or 'dpkg --list | grep libmuffin0' for Mint/Ubuntu)

equery l muffin
 * Searching for muffin ...
[IP-] [  ] x11-wm/muffin-5.4.7:0

 * Distribution - Gentoo

 * Graphics hardware *and* driver used

audiolab /usr/portage/x11-wm/muffin # lspci -k
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
	DeviceName:  Onboard IGD
	Subsystem: Dell Haswell-ULT Integrated Graphics Controller
	Kernel driver in use: i915
	Kernel modules: i915

 * 64 bit
 Linux audiolab 5.15.69-gentoo #1 SMP PREEMPT Tue Sep 27 08:20:56 CEST 2022 x86_64 Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz GenuineIntel GNU/Linux
 ```

**Issue**

After upgrading from v5.2 to v5.4,  shortcut keys for window menu are not present.

**Steps to reproduce**

1. Open any application in a Cinnamon session.
2. Press `<alt><space>` to display window menu.
3. Press `x` to maximise the window.

**Expected behaviour**

The opened window would be maximised after `x` is pressed.  The menu would also indicate, with an underscore, which keys were bound to a specific menu item. (This issue affects all menu items, not just maximise)

**Other information**

I created a new system account and logged in to perform the same test.  It doesn't have any shortcut keys either, so I don't think it's related to user profile.

**Comment by KrisPatAU** [comment]
I can confirm this issue in 5.15.0-53

All the handy shortcuts (alt+space, x, alt+space, c) on window menu are missing. I've tried changing themes, etc. but nothing works.

**Comment by nzlosh** [comment]
Fixed in future version, closing.
