### ISSUE TITLE
Window Snapping Disabled

### ISSUE THREAD

**Issue by mdisante** [linuxmint/muffin#662]
* linux mint 21.1
* cinnamon
* 64 bit
* patch level current - none outstanding
* Nvidia GTX970 mobile GPU
* nvidia-driver-525 (latest available)

Until very recently, window snapping (press window key on keyboard plus the left or right arrow key) was working fine. Suddenly it has stopped working. When I searched for this issue online, I find that window snapping was 'silently' dropped from linux mint 21.1. What would it take to have window snapping reinstated??? I use this feature constantly and it is really cramping my style not having it.

To reproduce the issue, just log onto linux mint 21.1 Cinnamon and open a window, then try to snap the window to the left or right half of the screen with the windows (super?) key plus left or right arrow. NOTHING happens.

The expected behavior is that the window should snap to the left or right half of the screen as requested.

**Comment by JosephMcc** [comment]
> To reproduce the issue, just log onto linux mint 21.1 Cinnamon and open a window, then try to snap the window to the left or right half of the screen with the windows (super?) key plus left or right arrow. NOTHING happens.

Actually this works exactly as expected for me on Mint21.1. Don't know what you are reading but this feature is still there and works just fine. The only time it shouldn't work is if you disable it in the "Window Tiling" settings or you are trying to tile a window that isn't capable of resizing to fit in one half of the screen.

**Comment by mdisante** [comment]
Well, it was working fine for me until very recently. Not sure exactly 
when it stopped working, but I would love to know what killed it?

I checked and Window Tiling is enabled.

**Comment by mdisante** [comment]
Okay, I finally figured out what was going on. The 'Windows' key on my keyboard had become disabled somehow. I unplugged the keyboard, rebooted and plugged it back in. Now everything is working properly. Sorry for the mix-up.
