### ISSUE TITLE
window tiling not working on secondary screen

### ISSUE THREAD

**Issue by JulianGro** [linuxmint/muffin#664]
```
 * Cinnamon 5.6.7
 * Debian Testing
 * Nvidia GTX 1080, with Nvidia proprietary 525.89.02
 * amd64/x86_64
 ```
[xsession-errors.log](https://github.com/linuxmint/cinnamon/files/11056109/xsession-errors.log)

### Issue
Trying to use window tiling on the bottom of a secondary monitor doesn't work. As in it doesn't even display the preview.
The bottom corners do the side tiling instead of the corner tiling.

### Steps to reproduce
Connect a second screen.
Move a window to the bottom of that screen.
-> Nothing happens.

### Expected behaviour
The tiling should work same as on the primary screen.

### Other information
Screenshot of my screen configuration:
![Bildschirm_001](https://user-images.githubusercontent.com/11144627/227355945-ac155fc5-8ef8-467a-b8bb-7064cdb61141.png)

**Comment by JosephMcc** [comment]
Ah, if it will tile to a lower corner then it should tile to the bottom half. In the OP's original post it didn't seem to be offering him the ability to tile to the two lower corners either.

**Comment by JulianGro** [comment]
Yeah it doesn't tile into either bottom corner on the secondary display for me.

This doesn't have anything to do with size by the way, especially since it works on the top.

**Comment by JosephMcc** [comment]
> This doesn't have anything to do with size by the way, especially since it works on the top.

I wonder if it has something to do with the way the monitors are aligned since their top and bottom edges don't line up. I'm curious if it behaves differently if you line up the top or bottom of the displays in the display settings?
