### ISSUE TITLE
Fractional scaling not available anymore since upgrade to 21.2

### ISSUE THREAD

**Issue by cissler** [linuxmint/muffin#672]
### Distribution

Mint 21.2

### Package version

5.8.4

### Graphics hardware in use

AMD 5600G

### Frequency

Always

### Bug description

Since the upgrade from 21.1 to 21.2 only 100%, 200%, 300% and 400% scaling options are available. Before I could select 125%, 150%, 175%, etc. as well.

### Steps to reproduce

Open display settings and find the formerly available fractional scaling options missing.

### Expected behavior

Be able to select fractional scaling options like in Mint 21.1, since 100% is too small on a 4k screen and 200% is too big.

### Additional information

Issue is being discussed here as well: https://forums.linuxmint.com/viewtopic.php?p=2357495

**Comment by mtwebster** [comment]
Enable it in the Display-> Settings tab
![image](https://github.com/linuxmint/muffin/assets/262776/f3638ee9-efcb-47d5-914c-32d1374c7fbe)

It was never meant to be enabled by default (it wasn't pre-mint21), as it won't work reliably on all computers.
