### ISSUE TITLE
Fails to compile with wayland and [-flto=auto -Werror=lto-type-mismatch] using GCC 13.2.1

### ISSUE THREAD

**Issue by SparkyBluefang** [linuxmint/muffin#698]
### Distribution

Gentoo

### Package version

6.0.1

### Frequency

Always

### Bug description

Downstream bug report: https://bugs.gentoo.org/933879

[muffin 6.0.1 build.log](https://github.com/user-attachments/files/16093254/build.log)
[muffin 6.2.0 build.log](https://github.com/user-attachments/files/16093449/build2.log)

```
../muffin-6.2.0/src/backends/meta-egl.h:117:12: error: type of ‘meta_egl_create_window_surface’ does not match original declaration [-Werror=lto-type-mismatch]
  117 | EGLSurface meta_egl_create_window_surface (MetaEgl            *egl,
      |            ^
../muffin-6.2.0/src/backends/meta-egl.c:389:1: note: type mismatch in parameter 4
  389 | meta_egl_create_window_surface (MetaEgl            *egl,
      | ^
../muffin-6.2.0/src/backends/meta-egl.c:389:1: note: type ‘EGLNativeWindowType’ should match type ‘void *’
../muffin-6.2.0/src/backends/meta-egl.c:389:1: note: ‘meta_egl_create_window_surface’ was previously declared here
../muffin-6.2.0/src/backends/meta-egl.c:389:1: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
lto1: some warnings being treated as errors
lto-wrapper: fatal error: x86_64-pc-linux-gnu-gcc returned 1 exit status
compilation terminated.
```

Initial report was for muffin `6.0.1`, but I have reproduced with muffin `6.2.0`

Assuming `mutter` doesn't have the same problem, I tired comparing the method signature of `meta_egl_create_window_surface` to upstream `mutter`, and it looks the same to me.

If there are any commits to backport, I wouldn't know what to look for. And it doesn't help (me) that `muffin` is pretty out of date compared to upstream.

### Steps to reproduce

Build with `-Dwayland=true` and `CFLAGS="$CFLAGS -flto=auto -Werror=lto-type-mismatch"`

### Expected behavior

Compiles without error

**Comment by leigh123linux** [comment]
Is there a gentoo mutter bug report to match?

https://github.com/search?q=repo%3AGNOME%2Fmutter%20meta_egl_create_window_surface&type=code

**Comment by SparkyBluefang** [comment]
I had to go back all the way to `mutter-3.38.4` to find a version with this compile error. Starting with `mutter-40.0` I was not able to reproduce.

I didn't find any Gentoo bugs for mutter, presumably because the older versions with the issue were dropped from the package tree before anyone started playing around with LTO builds.

**Comment by leigh123linux** [comment]
You are using plain build type?, -fno-strict-aliasing should suppress this

https://github.com/linuxmint/muffin/blob/master/meson.build#L302

**Comment by eli-schwartz** [comment]
What? That's not a warning flag.

That flag modifies codegen to "hopefully" produce slower code that assumes you're writing invalid C (because violating the aliasing rules of the C language is, well, violating the requirements for validity).

It's a hope and a prayer, not a guarantee of correctness.

**Comment by SparkyBluefang** [comment]
To be fair, mutter also has that flag for non-plain builds
https://gitlab.gnome.org/GNOME/mutter/-/blob/8e9d13aa3b3baa099ca32bbcb10afb4d9eea4460/meson.build#L486

However, the Gentoo mutter packages also do plain builds by default, and only do debug builds if the debug use-flag is enabled.

So it would seem mutter had some code or meson change that addressed this error.

**Comment by leigh123linux** [comment]
I guess this is the expected result when you use -Werror=lto-type-mismatch, the code compiles fine with gcc-14 without that flag.

```
/usr/lib64/libgbm.so /usr/lib64/libsystemd.so -Wl,--end-group
../src/backends/meta-egl.h:117:12: warning: type of ‘meta_egl_create_window_surface’ does not match original declaration [-Wlto-type-mismatch]
  117 | EGLSurface meta_egl_create_window_surface (MetaEgl            *egl,
      |            ^
../src/backends/meta-egl.c:389:1: note: type mismatch in parameter 4
  389 | meta_egl_create_window_surface (MetaEgl            *egl,
      | ^
../src/backends/meta-egl.c:389:1: note: type ‘EGLNativeWindowType’ should match type ‘void *’
../src/backends/meta-egl.c:389:1: note: ‘meta_egl_create_window_surface’ was previously declared here
../src/backends/meta-egl.c:389:1: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
```

If gentoo wants to use  -Werror=lto-type-mismatch and break stuff they can fix the fallot.

**Comment by mtwebster** [comment]
ref: https://gitlab.gnome.org/GNOME/mutter/-/issues/1033

**Comment by thesamesam** [comment]
> If gentoo wants to use -Werror=lto-type-mismatch and break stuff they can fix the fallout.

This is based on a misunderstanding - it's also not particularly constructive to say this, IMO.

>  the code compiles fine with gcc-14 without that flag.

It compiles and the result _isn't necessarily correct_.

The messages you quote have:
> ../src/backends/meta-egl.c:389:1: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used

The code is buggy and broken anyway. If muffin isn't interested in fixing it, it should be built with `-fno-strict-aliasing` specified in the build system.

In this specific case, `lto-type-mismatch` is a diagnostic which only shows up with LTO but exposes existing latent undefined behaviour.

**Comment by thesamesam** [comment]
In terms of the technical problem here..

`eglplatform.h` does the following:
```c
#if defined(EGL_NO_PLATFORM_SPECIFIC_TYPES)

typedef void *EGLNativeDisplayType;
typedef void *EGLNativePixmapType;
typedef void *EGLNativeWindowType;
/* ... */
#elif defined(WL_EGL_PLATFORM)

typedef struct wl_display     *EGLNativeDisplayType;
typedef struct wl_egl_pixmap  *EGLNativePixmapType;
typedef struct wl_egl_window  *EGLNativeWindowType;
/* ... */
#elif defined(USE_X11)

/* X11 (tentative)  */
#include <X11/Xlib.h>
#include <X11/Xutil.h>

typedef Display *EGLNativeDisplayType;
typedef Pixmap   EGLNativePixmapType;
typedef Window   EGLNativeWindowType;
/* ... */
```

I see many `config.h` fixes in mutter which likely fixed this. Finding the specific commit is a pain so far because a lot of refactoring occurred.

**Comment by SparkyBluefang** [comment]
For the record, I managed to shoehorn a hacked together ebuild to bisect mutter commits.

https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1514

Specifically, the build stared succeeding with this commit:
https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1514/diffs?commit_id=3e4ece50d3fbf60bbc241129ba11c642588f4a1a

Looks like this was an accidental fix of the LTO issue. I doubt any of this is easily back-portable without just rebasing on a newer version.

Probably not worth addressing until there's more consensus on what the future of muffin looks like (i.e. linuxmint/wayland/issues/25, linuxmint/wayland/issues/33). But I suspect it will be sticking around, and at some point there will be another major rebase that will pick up these changes.

For the time being, the LTO lags have just been filtered out in the Gentoo packages.

**Comment by leigh123linux** [comment]
> > If gentoo wants to use -Werror=lto-type-mismatch and break stuff they can fix the fallout.
> 
> This is based on a misunderstanding - it's also not particularly constructive to say this, IMO. It is not a great thing to say to a bug report filed in good faith.
> 
> > the code compiles fine with gcc-14 without that flag.
> 
> It compiles and the result _isn't necessarily correct_.
> 
> The messages you quote have:
> 
> > ../src/backends/meta-egl.c:389:1: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
> 
> The code is buggy and broken anyway. If muffin isn't interested in fixing it, it should be built with `-fno-strict-aliasing` specified in the build system _unconditionally_, not based on build type.
> 
> In this specific case, `lto-type-mismatch` is a diagnostic which only shows up with LTO but exposes existing latent undefined behaviour.
 

I disagree, gentoo shouldn't force -Werror=lto-type-mismatch, if they do, they can add `-fno-strict-aliasing` to their ebuild to fix.
As for LTO, I have been building the cinnamon stack with LTO optimisations for a couple of years without issue.

**Comment by SparkyBluefang** [comment]
> I disagree, gentoo shouldn't force -Werror=lto-type-mismatch, if they do, they can add `-fno-strict-aliasing` to their ebuild to fix.

I think that was the misunderstanding. Gentoo is not forcing either LTO or -Werror=lto-type-mismatch.
https://bugs.gentoo.org/618550
https://marc.info/?l=gentoo-dev&m=165639574126280&w=2

As far as I'm aware, there is no intent to set any LTO related flags by default (though I could be wrong). This was from a tinderbox that was checking the package tree for LTO build errors and code smells, to ensure packages behave correctly should an end user choose to set these C[XX]FLAGS. However, the LTO user guide does recommend setting `-Werror=lto-type-mismatch -Werror=strict-aliasing` as a safety measure, probably to ensure users aren't left with an inoperable or unstable system.
https://wiki.gentoo.org/wiki/LTO

But either way, I have zero skin in the game. I'm just a proxy package maintainer and I was asked if this was reported upstream. At this point, I'll butt-out. I've done my duty and diligence, and I'll leave any continuing conversation to actual Gentoo devs. I have no interest being caught in the middle :)

**Comment by thesamesam** [comment]
> I disagree, ...

It's not clear to me what you disagree with or why.
