### ISSUE TITLE
no search window in gedit 3.6.2

### ISSUE THREAD

**Issue by daschuer** [linuxmint/muffin#90]
In Ubuntu Raring with cinnamon 1.8.6 and muffin 1,8,2, gedit 3.6.2 does not display its small search window.
The window seems only be hidden, because search works as usual but without the windows. The replace window works without issues. 

I am not sure if this is the right place to report, but it depends on cinnamon/muffin, because there is no issue when switching to unity. 

I have also found a similar report here:
https://bugzilla.redhat.com/show_bug.cgi?id=840297

**Comment by JosephMcc** [comment]
Is this still an issue in 2.8? Would you mind closing it if not?

**Comment by daschuer** [comment]
I cannot reproduce the issue on Ubuntu Trusty 
gedit 3.10.4-0ubuntu4
cinnamon 2.6.13
muffin 2.6.1
