### ISSUE TITLE
Cinnamon taskbar don't work when iBus input-method activated.

### ISSUE THREAD

**Issue by miurahr** [linuxmint/muffin#93]
The window switch feature  on task bar is not working when iBus input-method is activated. 

Here is a screen capture when problem occurs:  https://dl.dropboxusercontent.com/u/90779460/Screenshot_from_2013-06-01bisect3.png  
captured with 1.7.4

I use ibus 1.4.1-3ubuntu1 and ibus-mozc/mozc-server 1.3.975.102-2ubuntu0.1 .

cinnamon/muffin 1.7.2 works well but be with issue #59.

I have bisected cinnamon and muffin then found muffin change https://github.com/linuxmint/muffin/commit/baba0ed3985d22827ace3ab347b7f4f57c8fdcb5 to fix #59 caused it.

**Comment by leigh123linux** [comment]
This pull request  should fix the issue https://github.com/linuxmint/muffin/pull/271

**Comment by leigh123linux** [comment]
Fixed

https://github.com/linuxmint/muffin/commit/5d6ec8b9fad2e21c05a820484e34998f515fa711
