### ISSUE TITLE
Add startup features to muffin

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/muffin#94]
It would be cool to have the possibility to start programs minimized, maximized, or on defined monitors by starting them from bash.

For example KDE offers the following:
kstart --iconify APPLICATION
to start the APPLICATION minimized

**Comment by DirkHaar** [comment]
Can be realized using devilspie:

[https://wiki.ubuntuusers.de/Devilspie/]
[https://wiki.gnome.org/action/show/Projects/DevilsPie?action=show&redirect=DevilsPie]

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
